// Dark Skies DLC

TIFactionTemplate.CampaignStart.ResistCouncil.2003=Saudações, {0}. É um prazer anunciar que {1} agora conta com a sua liderança. Eu sou {2}, sua chefe de estado-maior.<br/><br/>Nós representamos um pequeno grupo que acredita a queda dos alienígenas e seu subsequente desaparecimento sejam uma potencial ameaça. Nossa intenção é formar uma organização capaz de investigar e, se necessário, combater quaisquer ameaças causadas pelos alienígenas.<br/><br/><h>Eu recomendo que um conselheiro seja enviado para investigar o local da colisão na região de {4} o mais rápido possível. É melhor que nossos outros conselheiros sejam usados para tentar ganhar influência nas nações que possam contribuir com recursos para nossa causa.</h><br/><br/>Você pode verificar os nossos objetivos a qualquer momento ao clicar no símbolo da nossa facção no canto superior à esquerda em sua tela. // rank, council name, leader name

TIFactionTemplate.leader.description.ResistCouncil.2003=Capitã, Corpo de Inteligência do Exército Real, ref. 1989; Diretora de Casos, local não divulgado, Serviço Secreto de Inteligência, 1989-1990; Intermediária do SSI do Grupo Trevi, 1991-1992; Chefe de Estação, Lagos, 1992-1995; Chefe de Estação, Islamabade, 1995-1997; Chefe Adjunta de Relações Africanas, 1997-1998; Assessora sênior de grupo insurgente, local não divulgado, 1999-presente.
TIFactionTemplate.leader.description.DestroyCouncil.2003=Paraquedista alistado na Guerra das Malvinas, condecorado por bravura na Batalha do Monte Longdon em 1982. Treinado na Escola das Américas do Exército dos EUA, 1976. Serviu como oficial comissionado ou assessor junto a várias unidades especiais de operações antiseparatistas e milícias na Venezuela, no Panamá e no Peru no fim dos anos 1980. Trabalhou na divisão latino-americana do Pentágono nos anos 1990. Em 1995, foi preso brevemente em Buenos Aires por acusações de crimes de guerra referentes a supostas ações durante a Operação Condor no início dos anos 1980. Absolvido em 1996.
TIFactionTemplate.leader.description.ExploitCouncil.2003=Vários cargos relacionados à fabricante de armas Western Armories, 1987-presente, incluindo presidente do conselho desde 1997. Investidor minoritário nas indústrias DWKY, parceira dos governos da Botsuana e da Namíbia na mineração de diamantes. A mídia ativista o critica ocasionalmente por certas práticas trabalhistas em seus diversos empreendimentos, mas não há nenhuma investigação formal aberta.
TIFactionTemplate.leader.description.EscapeCouncil.2003=Mestre em Física e Filosofia, Universidade de Oxford, 1991; Investidor principal, Al Zaabi Comunicações por Satélite. Famoso por apoiar financeiramente várias publicações e organizações entusiastas pelo espaço.
TIFactionTemplate.leader.description.SubmitCouncil.2003=Frequentou o Seminário Teológico Batista do Sudoeste, Fort Worth, Texas, o abandonou em 1995 sem se graduar. Acusada de incitação e transporte de substâncias controladas relacionadas ao suicídio em massa de membros do culto da Fonte Eterna no Arizona em 1997; as acusações foram abandonadas posteriormente. Trabalhou como gestora de conteúdo para uma variedade de sites <i>new age</i> originados na Califórnia que previam a chegada alienígena nas décadas vindouras, 1998-presente, período no qual ela se tornou uma famosa palestrante e guru de autoajuda.
TIFactionTemplate.leader.description.AppeaseCouncil.2003=B.A. em Ciência Politica, Universidade de Chenai, 1968, onde era ativista de direitos civis. Foi baleado pela polícia durante um protesto em Muzaffarnagar, Uttar Pradesh em 1967. Residiu em Vancouver, Canadá, 1967-1973. Trabalhou como observador civil e ouvidor de operações de paz da ONU em diversos locais, incluindo Baluchistão, El Salvador e Moldávia, 1973-1993. Mestre em Direito com foco em legislatura internacional de direitos humanos, Universidade de Concórdia, 1977. Testemunhou em julgamentos de crimes de guerra e de acusações a mediadores de paz que cometeram ofensas graves durante missões. Desde 1993, tem servido como assessor a diversas organizações de paz e de direitos humanos.
TIFactionTemplate.leader.description.CooperateCouncil.2003=B.S. em Engenharia Aeroespacial, Universidade Tsinghua, 1983; MS e PhD em Química, Instituto de Tecnologia de Massachusetts, 1987; PhD em Administração Pública, Universidade Tsinghua, 1990; Professora de Administração de Políticas Tecnológicas e Científicas, Universidade Jiaotong de Xiam, 1991-presente; Diretora, Departamento de Educação Superior, Ministério da Educação, 1997-2000.