
//Dark Skies DLC

TITechTemplate.displayName.BS_DemocratizationofSpace=Democratização do espaço
TITechTemplate.quote.BS_DemocratizationofSpace="Mesmo nossas melhores tecnologias nos permitem ver apenas 5% de nosso universo. Imagine o que poderíamos descobrir quando pudermos olhar para o resto dos 95%."<br/><align=right>{cooperateLeader}<align=left><br/><align=right>Do discurso de abertura da Conferência Anual de Astrônomos.<align=left>
TITechTemplate.summary.BS_DemocratizationofSpace=Avanços na tecnologia aeroespacial abrem os céus para mais pessoas.
TITechTemplate.description.BS_DemocratizationofSpace=A órbita terrestre baixa, cheia de milhares de novos satélites, agora é um testamento das mudanças trazidas à tona por um punhado de companhias de voo espacial privadas. Com a melhora no reuso de foguetes, uma abordagem de pesquisa e desenvolvimento menos adversa a riscos, e avanços na tecnologia de satélites que os permitem ser menores e mais leves, o custo de colocar massa em órbita caiu em mais de 80%. O resultado foi uma expansão sem precedentes do uso de satélites para fins acadêmicos e comerciais. Em paralelo, novos programas espaciais estão tomando forma em potências medianas e emergentes pelo mundo. A maior acessibilidade e interesse no espaço levaram a outros avanços na exploração espacial. Em particular, nossa habilidade de rastrear objetos próximos melhorou consideravelmente.

TITechTemplate.displayName.BS_ExascaleComputing=Computação em exaescala
TITechTemplate.quote.BS_ExascaleComputing="Sim, o conhecimento é poder, mas poder para qual propósito, Ifechi? Eu quero acreditar que quanto mais aprendemos, mais crescemos. Mas quanto mais velho eu fico, mais dificuldade eu tenho em escapar do sentimento de que estamos perigosamente perto do fruto proibido do mito."<br/><align=right>{appeaseLeader}<align=left><br/><align=right>Fragmento de uma carta a sua parceira enquanto cumpria missão no Senegal.<align=left>
TITechTemplate.summary.BS_ExascaleComputing=Nós construímos sistemas capazes de responder nossas perguntas científicas mais difíceis. 
TITechTemplate.description.BS_ExascaleComputing=Conforme nossos bancos de dados crescem e nossas simulações ficam cada vez mais sofisticadas, nós precisamos de computadores mais poderosos para lidar com eles. O caminho a este ponto não foi linear. Considerando as rotas mais óbvias de melhora, só os requerimentos de energia já teriam impossibilitado este projeto. Milhões de computadores trabalhando juntos em perfeita harmonia, falhando com graça e operando com uma eficiência energética inacreditável. Mas, por fim, nós conseguimos, e os lucros têm sido imensos. Avanços em enovelamento de proteína e mapeamento do genoma, ciência de materiais, modelos climáticos, simulações de engenharia, cosmologia e quase todos os outros campos de pesquisa científica trouxeram a humanidade a um pináculo de conhecimento a um precipício de tecnologia.

TITechTemplate.displayName.BS_DigitalSociety=Sociedade digital
TITechTemplate.quote.BS_DigitalSociety="Enterrem isso em algum lugar dos termos de licenciamento. Ninguém lê essas coisas e a maioria das pessoas não entende que se eles não estão pagando por um produto, eles <i>são</i> o produto."<br/><align=right>{exploitLeader}<align=left><br/><align=right>Comentários durante uma revisão interna de produto com a Freesoft Insights.</i><align=left>
TITechTemplate.summary.BS_DigitalSociety=O mundo se torna conectado de formas novas e, potencialmente, desestabilizadoras. 
TITechTemplate.description.BS_DigitalSociety=O invento de smartphones, a adoção em massa de redes sociais, marketing direcionado, redes de bots, a vigilância onipresente e sofisticadas campanhas de desinformação online. Qualquer um desses elementos poderia alterar o mundo por conta própria, mas, em vez disso, estão todos acontecendo ao mesmo tempo, além de incontáveis outras mudanças em nossas formas de viver. A era do algoritmos chegou e nossos problemas estão se multiplicando mais rápido do que podemos encontrar soluções. É neste mundo estranho e caótico da inovação combinado com pessimismo que algo fundamentalmente novo entrou. A questão é: este é ainda outro problema ou é a tão esperada solução. 