// Dark Skies DLC

TIFactionTemplate.leader.description.ResistCouncil.BrokenEarth=Capitã, Forças Reais da Comunidade das Nações, ref. 2098; Oficial de Casos, local não divulgado, Serviço Secreto de Inteligência, 2098-2099; Intermediária do SSI no Centro Contraterrorismo Australiano, 2100-2101; Chefe de Estação, Lagos, 2101-2103; Chefe de Estação, Rawalpindi, 2103-2105; Chefe Adjunta de Relações Africanas, 2105-2106; Assessora sênior de grupo insurgente, local não divulgado, 2107-presente.
TIFactionTemplate.leader.description.DestroyCouncil.BrokenEarth=Paraquedista alistado na Guerra de Laredo, condecorado por bravura na Batalha da Brecha das Cerdas em 2084. Treinado na Academia Pan-americana de Segurança, 2087. Serviu como oficial comissionado ou assessor junto a várias unidades de operações especiais antiseparatistas e milícias na Venezuela, no Panamá e no Peru nos anos 2080. Em 2107, foi preso brevemente em Buenos Aires por acusações de crimes de guerra referentes a supostas ações durante a Operação Condor no início dos anos 2080. Absolvido em 2108.
TIFactionTemplate.leader.description.ExploitCouncil.BrokenEarth=Vários cargos relacionados à fabricante de armas Western Armories, 2096-presente, incluindo presidente do conselho desde 2106. Investidor minoritário nas indústrias DWKY, parceira dos governos da Botsuana e da Namíbia na mineração de diamantes. A mídia ativista o critica ocasionalmente por certas práticas trabalhistas em seus diversos empreendimentos, mas não há nenhuma investigação formal aberta.
TIFactionTemplate.leader.description.EscapeCouncil.BrokenEarth=Mestre em Física e Filosofia, Universidade de Alexandria, 2100; Investidor principal, Al Zaabi Comunicações por Satélite; Diretor Adjunto de Administração. Famoso por apoiar financeiramente várias publicações e organizações entusiastas pelo espaço.
TIFactionTemplate.leader.description.SubmitCouncil.BrokenEarth=Frequentou o Seminário Teológico Batista do Sudoeste, Fort Worth, Texas, o abandonou em 2094 sem se graduar. Acusada de incitação e transporte de substâncias controladas relacionadas ao suicídio em massa de membros do culto da Fonte Eterna no Arizona em 2096; as acusações foram abandonadas posteriormente. Trabalhou como gestora de conteúdo para uma variedade de sites <i>new age</i> originados na Califórnia que previam a chegada alienígena nas décadas vindouras, 2097-presente, período no qual ela se tornou uma famosa palestrante e guru de autoajuda.
TIFactionTemplate.leader.description.AppeaseCouncil.BrokenEarth=B.A. em Ciência Politica, Universidade de Chenai, 2075, onde era ativista de direitos civis. Foi baleado pela polícia durante um protesto em Muzaffarnagar, Uttar Pradesh em 2076. Residiu em Vancouver, Canadá, 2076-2082. Trabalhou como observador civil em operações de paz em diversos locais, incluindo Baluchistão, Tamaulipas e Moldávia, 2082-2102. Mestre em Direito com foco em legislatura internacional de direitos humanos, Universidade de Sydney, 2084. Testemunhou em julgamentos de crimes de guerra e de acusações a mediadores de paz que cometeram ofensas graves durante missões. Desde 2102, tem servido como assessor a diversas organizações de paz e de direitos humanos.
TIFactionTemplate.leader.description.CooperateCouncil.BrokenEarth=B.S. em Engenharia Aeroespacial, Universidade Tsinghua, 2078; MS e PhD em Química, Instituto de Tecnologia de Massachusetts, 2082; PhD em Administração Pública, Universidade Tsinghua, 2085; Professora de Administração de Políticas Tecnológicas e Científicas, Universidade Jiaotong de Xiam, 2088-presente; Diretora, Liga C62, 2104-2107.
