TIRegionTemplate.displayName.Czechia.BrokenEarth=Brno
TIRegionTemplate.displayName.Hungary.BrokenEarth=Szeged
TIRegionTemplate.displayName.Bulgaria.BrokenEarth=Varna
TIRegionTemplate.displayName.Romania.BrokenEarth=Targoviste
TIRegionTemplate.displayName.Poland.BrokenEarth=Krakow
TIRegionTemplate.displayName.Moskva.BrokenEarth=Novomoskovsk
TIRegionTemplate.displayName.Kiev.BrokenEarth=Lviv
TIRegionTemplate.displayName.Volga.BrokenEarth=Samara
TIRegionTemplate.displayName.Rostovskaya.BrokenEarth=Volgograd
TIRegionTemplate.displayName.Donetsk.BrokenEarth=Luhansk
TIRegionTemplate.displayName.WesternSiberia.BrokenEarth=Omsk
TIRegionTemplate.displayName.Urals.BrokenEarth=Tyumen
TIRegionTemplate.displayName.Kirov.BrokenEarth=Sernorechensk
TIRegionTemplate.displayName.Novgorod.BrokenEarth=Novgorod
TIRegionTemplate.displayName.Belarus.BrokenEarth=Mogilev
TIRegionTemplate.displayName.Belgium.BrokenEarth=Bruges
TIRegionTemplate.displayName.Bavaria.BrokenEarth=Schwanenstadt
TIRegionTemplate.displayName.England.BrokenEarth=Oxford
TIRegionTemplate.displayName.Netherlands.BrokenEarth=Groningen
TIRegionTemplate.displayName.EnglishMidlands.BrokenEarth=Sheffield
TIRegionTemplate.displayName.Kaliningrad.BrokenEarth=Krolewiec
TIRegionTemplate.displayName.Paris.BrokenEarth=Chartres
TIRegionTemplate.displayName.EastGermany.BrokenEarth=Potsdam
TIRegionTemplate.displayName.Texas.BrokenEarth=Texarkana
TIRegionTemplate.displayName.RockyMountains.BrokenEarth=Boulder
TIRegionTemplate.displayName.Boise.BrokenEarth=Cheyenne
TIRegionTemplate.displayName.California.BrokenEarth=Las Vegas
TIRegionTemplate.displayName.RustBelt.BrokenEarth=Nova Chicago
TIRegionTemplate.displayName.Cascadia.BrokenEarth=Saint Rose
TIRegionTemplate.displayName.Florida.BrokenEarth=Fort Repose
TIRegionTemplate.displayName.Sydney.BrokenEarth=Broken Hill
TIRegionTemplate.displayName.Darwin.BrokenEarth=Cidadela
TIRegionTemplate.displayName.NewYork.BrokenEarth=Hudson
TIRegionTemplate.displayName.NewEngland.BrokenEarth=Providence
TIRegionTemplate.displayName.Shenandoah.BrokenEarth=Monument
TIRegionTemplate.displayName.Ontario.BrokenEarth=Kitchener
TIRegionTemplate.displayName.GreatPlains.BrokenEarth=Jericho
TIRegionTemplate.displayName.Lyon.BrokenEarth=Bugarach
TIRegionTemplate.displayName.Dixie.BrokenEarth=Savannah
TIRegionTemplate.displayName.HighPlains.BrokenEarth=Topeka

TIRegionTemplate.displayNameSentIn.Czechia.BrokenEarth=na região de Brno
TIRegionTemplate.displayNameSentIn.Hungary.BrokenEarth=na região de Szeged
TIRegionTemplate.displayNameSentIn.Bulgaria.BrokenEarth=na região de Varna
TIRegionTemplate.displayNameSentIn.Romania.BrokenEarth=na região de Targoviste
TIRegionTemplate.displayNameSentIn.Poland.BrokenEarth=na região de Krakow
TIRegionTemplate.displayNameSentIn.Moskva.BrokenEarth=na região de Novomoskovsk
TIRegionTemplate.displayNameSentIn.Kiev.BrokenEarth=na região de Lviv
TIRegionTemplate.displayNameSentIn.Volga.BrokenEarth=na região de Samara
TIRegionTemplate.displayNameSentIn.Rostovskaya.BrokenEarth=na região de Volgograd
TIRegionTemplate.displayNameSentIn.Donetsk.BrokenEarth=na região de Luhansk
TIRegionTemplate.displayNameSentIn.WesternSiberia.BrokenEarth=na região de Omsk
TIRegionTemplate.displayNameSentIn.Urals.BrokenEarth=na região de Tyumen
TIRegionTemplate.displayNameSentIn.Kirov.BrokenEarth=na região de Sernorechensk
TIRegionTemplate.displayNameSentIn.Novgorod.BrokenEarth=na região de Novgorod
TIRegionTemplate.displayNameSentIn.Belarus.BrokenEarth=na região de Mogilev
TIRegionTemplate.displayNameSentIn.Belgium.BrokenEarth=na região de Bruges
TIRegionTemplate.displayNameSentIn.Bavaria.BrokenEarth=na região de Schwanenstadt
TIRegionTemplate.displayNameSentIn.England.BrokenEarth=na região de Oxford
TIRegionTemplate.displayNameSentIn.Netherlands.BrokenEarth=na região de Gronigen
TIRegionTemplate.displayNameSentIn.EnglishMidlands.BrokenEarth=na região de Sheffield
TIRegionTemplate.displayNameSentIn.Kaliningrad.BrokenEarth=na região de Krolewiec
TIRegionTemplate.displayNameSentIn.Paris.BrokenEarth=na região de Chartres
TIRegionTemplate.displayNameSentIn.EastGermany.BrokenEarth=na região de Potsdam
TIRegionTemplate.displayNameSentIn.Texas.BrokenEarth=na região de Texarkana
TIRegionTemplate.displayNameSentIn.RockyMountains.BrokenEarth=na região de Boulder
TIRegionTemplate.displayNameSentIn.Boise.BrokenEarth=na região de Cheyenne
TIRegionTemplate.displayNameSentIn.California.BrokenEarth=na região de Las Vegas
TIRegionTemplate.displayNameSentIn.RustBelt.BrokenEarth=na região de Nova Chicago
TIRegionTemplate.displayNameSentIn.Cascadia.BrokenEarth=na região de Saint Rose
TIRegionTemplate.displayNameSentIn.Florida.BrokenEarth=na região de Fort Repose
TIRegionTemplate.displayNameSentIn.Sydney.BrokenEarth=na região de Broken Hill
TIRegionTemplate.displayNameSentIn.Darwin.BrokenEarth=na região de Citadel
TIRegionTemplate.displayNameSentIn.NewYork.BrokenEarth=na região de Hudson
TIRegionTemplate.displayNameSentIn.NewEngland.BrokenEarth=na região de Providence
TIRegionTemplate.displayNameSentIn.Shenandoah.BrokenEarth=na região de Monument
TIRegionTemplate.displayNameSentIn.Ontario.BrokenEarth=na região de Kitchener
TIRegionTemplate.displayNameSentIn.GreatPlains.BrokenEarth=na região de Jericho
TIRegionTemplate.displayNameSentIn.Lyon.BrokenEarth=na região de Bugarach
TIRegionTemplate.displayNameSentIn.Dixie.BrokenEarth=na região de Savannah
TIRegionTemplate.displayNameSentIn.HighPlains.BrokenEarth=na região de Topeka

TIRegionTemplate.displayNameSentOf.Czechia.BrokenEarth=da região de Brno
TIRegionTemplate.displayNameSentOf.Hungary.BrokenEarth=da região de Szeged
TIRegionTemplate.displayNameSentOf.Bulgaria.BrokenEarth=da região de Varna
TIRegionTemplate.displayNameSentOf.Romania.BrokenEarth=da região de Targoviste
TIRegionTemplate.displayNameSentOf.Poland.BrokenEarth=da região de Krakow
TIRegionTemplate.displayNameSentOf.Moskva.BrokenEarth=da região de Novomoskovsk
TIRegionTemplate.displayNameSentOf.Kiev.BrokenEarth=da região de Lviv
TIRegionTemplate.displayNameSentOf.Volga.BrokenEarth=da região de Samara
TIRegionTemplate.displayNameSentOf.Rostovskaya.BrokenEarth=da região de Volgograd
TIRegionTemplate.displayNameSentOf.Donetsk.BrokenEarth=da região de Luhansk
TIRegionTemplate.displayNameSentOf.WesternSiberia.BrokenEarth=da região de Omsk
TIRegionTemplate.displayNameSentOf.Urals.BrokenEarth=da região de Tyumen
TIRegionTemplate.displayNameSentOf.Kirov.BrokenEarth=da região de Sernorechensk
TIRegionTemplate.displayNameSentOf.Novgorod.BrokenEarth=da região de Novgorod
TIRegionTemplate.displayNameSentOf.Belarus.BrokenEarth=da região de Mogilev
TIRegionTemplate.displayNameSentOf.Belgium.BrokenEarth=da região de Bruges
TIRegionTemplate.displayNameSentOf.Bavaria.BrokenEarth=da região de Schwanenstadt
TIRegionTemplate.displayNameSentOf.England.BrokenEarth=da região de Oxford
TIRegionTemplate.displayNameSentOf.Netherlands.BrokenEarth=da região de Gronigen
TIRegionTemplate.displayNameSentOf.EnglishMidlands.BrokenEarth=da região de Sheffield
TIRegionTemplate.displayNameSentOf.Kaliningrad.BrokenEarth=da região de Krolewiec
TIRegionTemplate.displayNameSentOf.Paris.BrokenEarth=da região de Chartres
TIRegionTemplate.displayNameSentOf.EastGermany.BrokenEarth=da região de Potsdam
TIRegionTemplate.displayNameSentOf.Texas.BrokenEarth=da região de Texarkana
TIRegionTemplate.displayNameSentOf.RockyMountains.BrokenEarth=da região de Boulder
TIRegionTemplate.displayNameSentOf.Boise.BrokenEarth=da região de Cheyenne
TIRegionTemplate.displayNameSentOf.California.BrokenEarth=da região de Las Vegas
TIRegionTemplate.displayNameSentOf.RustBelt.BrokenEarth=da região de Nova Chicago
TIRegionTemplate.displayNameSentOf.Cascadia.BrokenEarth=da região de Saint Rose
TIRegionTemplate.displayNameSentOf.Florida.BrokenEarth=da região de Fort Repose
TIRegionTemplate.displayNameSentOf.Sydney.BrokenEarth=da região de Broken Hill
TIRegionTemplate.displayNameSentOf.Darwin.BrokenEarth=da região de Citadel
TIRegionTemplate.displayNameSentOf.NewYork.BrokenEarth=da região de Hudson
TIRegionTemplate.displayNameSentOf.NewEngland.BrokenEarth=da região de Providence
TIRegionTemplate.displayNameSentOf.Shenandoah.BrokenEarth=da região de Monument
TIRegionTemplate.displayNameSentOf.Ontario.BrokenEarth=da região de Kitchener
TIRegionTemplate.displayNameSentOf.GreatPlains.BrokenEarth=da região de Jericho
TIRegionTemplate.displayNameSentOf.Lyon.BrokenEarth=da região de Bugarach
TIRegionTemplate.displayNameSentOf.Dixie.BrokenEarth=da região de Savannah
TIRegionTemplate.displayNameSentOf.HighPlains.BrokenEarth=da região de Topeka