
// Dark Skies DLC

TINarrativeEventTemplate.displayName.event_AlienAwareness=公众对外星人的认知
TINarrativeEventTemplate.event_AlienAwareness.summary=我们再也无法否认，外星人已经进入了我们的世界，而且正在活动。
TINarrativeEventTemplate.event_AlienAwareness.query=无可辩驳的证据已公诸于世——包括大量不同来源的目击证词、经过核实的视频影像，甚至经过认证的实物证据，证明了地外生命存在于太阳系之中。<br/><br/>不言而喻，这一消息对广大公众造成了巨大冲击。人们的反应各不相同，有人恐惧，也有人充满希望；甚至有些人感到愤怒——他们并非针对外星人本身而愤怒，而是对本国政府心怀不满，他们认为政府早已知晓这一切，却刻意向公众隐瞒。<br/><br/>在这场滔天巨浪之中，或许也带来了一个立竿见影的积极转变：外星人的确存在这一事实，似乎唤醒了当代人的关注与思考。各地招募机构和征兵部门报告称，人们对科学和军事领域的兴趣显著上升；一些才华横溢且社会关系深厚的精英人士也联系到了我们的特工，希望在这场变局中能有所作为。
TINarrativeEventTemplate.event_AlienAwareness.option0=无论好坏，人类已然觉醒。
TINarrativeEventTemplate.event_AlienAwareness.optionDetail0=<skip/>
TINarrativeEventTemplate.event_AlienAwareness.optionResult0={summary}

TINarrativeEventTemplate.displayName.event_2003_AlienCyberattack=外星网络攻击
TINarrativeEventTemplate.event_2003_AlienCyberattack.summary=全球所有先进军事力量均报告出现大规模设备故障。
TINarrativeEventTemplate.event_2003_AlienCyberattack.query=外星人似乎已将一套高度复杂的恶意软件，植入了世界各国军队及国防承包商使用的通信与后勤系统软件中。尽管我们的专家仍在努力破解目前获取的少量代码片段，但我们认为，此次事件很可能发生在地球上的{secondaryTargetNationNameWithArticle}建立之后，而且无疑得到了当地合作者的协助。
TINarrativeEventTemplate.event_2003_AlienCyberattack.option0=我们的国防，是否已陷入对技术的过度依赖？
TINarrativeEventTemplate.event_2003_AlienCyberattack.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_AlienCyberattack.optionResult0={summary}

//// ALT-HISTORY EVENTS

TINarrativeEventTemplate.displayName.event_2003_MissionAccomplished=任务完成
TINarrativeEventTemplate.event_2003_MissionAccomplished.summary=美国总统今天宣布，在伊拉克的主要作战行动已经结束。
TINarrativeEventTemplate.event_2003_MissionAccomplished.query=在一场引人注目的入场仪式中，一架美国海军喷气式战斗机在航空母舰上实施了拦阻着舰，随后总统表示，尽管仍有许多艰难工作有待完成，但美国及其盟友已成功击败了前伊拉克独裁政权。<br/><br/>这场军事力量的胜利展示标志着反恐战争迎来重大转折点，再次凸显了美国在全球范围内的主导地位。然而，批评者迅速指出，伊拉克战争缺乏正当性，可能会导致更广泛的地区陷入动荡，而且认为总统的整场演讲不过是场毫无必要、耗资巨大的政治作秀。
TINarrativeEventTemplate.event_2003_MissionAccomplished.option0=既然外星人已经到来，这些事真的还有那么重要吗？
TINarrativeEventTemplate.event_2003_MissionAccomplished.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_MissionAccomplished.optionResult0={summary}

TINarrativeEventTemplate.displayName.event_2003_ColumbiaDisaster=哥伦比亚号航天飞机事故
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.summary=2003 年 2 月 1 日，<i>哥伦比亚号</i>航天飞机穿过德克萨斯州和路易斯安那州上空，在重返大气层时解体，七名宇航员全部遇难。
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.query=起初，人们认为这场事故虽然令人悲痛，却尚属寻常，但就在一个月后，一个神秘的太空物体突然出现，让这起事件变得争议不断。尽管官方调查仍在进行中，但各种越来越复杂的阴谋论已开始将这两起事件联系起来。有人因安全问题主张缩减载人太空飞行计划，也有人认为现在正是推动改革、加大投入的关键时机。
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.option0=我们应该关注眼下更紧迫的问题。
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.optionResult0={targetFactionNameCap}同意削减对载人太空计划的支持。
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.option1=现在不是害怕的时候！
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.optionResult1={targetFactionNameCap}决定加大对载人太空计划的支持。
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.option2=正如他们所计划的那样。
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_ColumbiaDisaster.optionResult2={targetFactionNameCap}同意削减对载人太空计划的支持。

TINarrativeEventTemplate.displayName.event_2003_AlienTacSim=外星人入侵战术模拟游戏发布
TINarrativeEventTemplate.event_2003_AlienTacSim.summary=一家知名游戏工作室刚刚推出了一款外星人入侵主题的全新电子游戏。
TINarrativeEventTemplate.event_2003_AlienTacSim.query=玩家要操控一支跨国准军事精锐组织，在全球战略层面与回合制战术层面之间切换，抵抗外星威胁。尽管这款游戏是另一款更早推出的同类游戏的精神续作，而且已经开发多年，但考虑到近期全球新闻的动向，人们不禁觉得其发布时间格外巧合。
TINarrativeEventTemplate.event_2003_AlienTacSim.option0=或许正是时代的某种征兆。
TINarrativeEventTemplate.event_2003_AlienTacSim.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_AlienTacSim.option0.outcome0=大获成功。
TINarrativeEventTemplate.event_2003_AlienTacSim.option0.outcome0.Summary=一款外星人入侵主题的全新电子游戏大获成功。
TINarrativeEventTemplate.event_2003_AlienTacSim.option0.outcome0.Detail=或许正是由于时机有利，这款游戏在全球市场取得了巨大成功。玩家们称赞其战斗系统营造出紧张刺激的解谜体验，而评论家则认为它为近年来发展停滞的这一类型游戏注入了新的活力。甚至已有传闻称，有人计划推出一个雄心勃勃的大型模组，让游戏变得规模更大、机制更复杂。
TINarrativeEventTemplate.event_2003_AlienTacSim.option0.outcome1=无人问津。
TINarrativeEventTemplate.event_2003_AlienTacSim.option0.outcome1.Summary=一款外星人入侵主题的全新电子游戏惨遭失利。
TINarrativeEventTemplate.event_2003_AlienTacSim.option0.outcome1.Detail=或许正是由于发布时机不详，该游戏未能在全球市场获得多少反响。玩家和评论家纷纷批评其难度过于残酷、用户界面难用，以及剧情单薄，甚至显得有些不合时宜。

TINarrativeEventTemplate.displayName.event_2003_DemocraticBacksliding=民主倒退
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.summary={targetNationNameWithArticleAndPlacePrep}的民主面临倒退的风险。
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.query=民粹派政客抨击精英机构，将经济状况恶化和{targetNationAdjective}的价值观衰退归咎于外来者和边缘群体，吸引了越来越多的支持者。社交媒体已从昔日的互联与学习工具，沦为虚假错误信息的泛滥之地。这些信息完美利用了平台算法的底层逻辑——即通过极力放大公众愤怒，来换取更高的用户活跃度。近期改革致使国家权力过度向行政机关集中，司法独立原则已遭到实质性破坏。<br/><br/>这一切固然令人担忧，但我方阵营中的一些人认为，我们也许可以利用这一情况，进一步巩固对{targetNationNameWithArticle}的控制。
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.option0=我们热爱民主，不是吗？
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionResult0={summary}
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.option1=煽动舆论，反对威胁到{targetNationNameWithArticle}的外部势力。
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionResult1={targetNationAdjective}的政客们煽动针对外部势力的舆论。
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.option2=遏制虚假信息的传播。
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionResult2={targetNationNameWithArticleCap}打击虚假新闻。
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.option3=扶持民间势力。
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionDetail3=<skip/>
TINarrativeEventTemplate.event_2003_DemocraticBacksliding.optionResult3={targetNationNameWithArticleCap}为民间势力提供了支持。

TINarrativeEventTemplate.displayName.event_2003_RisingAuthoritarianism=威权主义抬头
TINarrativeEventTemplate.event_2003_RisingAuthoritarianism.summary=一种令人担忧的趋势正在全球的民主国家中蔓延。
TINarrativeEventTemplate.event_2003_RisingAuthoritarianism.query=在千禧年交替之际，一股民主浪潮席卷世界。众多前专制政权相继垮台，人们曾以为即将迎来自由的新时代。<br/><br/>然而遗憾的是，人们后来发现，许多新建立的民主政体基础薄弱，极易受到个人崇拜式领袖及政党的裹挟，而这些势力上台后反而开始瓦解当初助其掌权的制度。日益加剧的不平等与失业、对社会经济变革的反弹，以及选举中的恶性竞争等，都可能是引起问题的原因。就算是历史更悠久、根基更稳固的民主国家也未能幸免。
TINarrativeEventTemplate.event_2003_RisingAuthoritarianism.option0=自由可不是理所当然的。
TINarrativeEventTemplate.event_2003_RisingAuthoritarianism.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_RisingAuthoritarianism.optionResult0={summary}

//// ALIEN MYSTERY EVENTS

TINarrativeEventTemplate.displayName.event_2003_PublicSpeculation=公众猜测
TINarrativeEventTemplate.event_2003_PublicSpeculation.summary=距离那个来自太空的神秘造访者已过去数月之久，然而由于缺乏可证实的官方信息，各种疯狂的无端猜测正在{targetNationAdjective}民间愈演愈烈。
TINarrativeEventTemplate.event_2003_PublicSpeculation.query=其中的许多猜测都毫无根据：有的指责{targetNationAdjective}政府和跨国精英阶层勾结以掩盖其不当行为，有的声称是官方捏造了这一事件，转移人们对其他问题的注意力，甚至指责他们与外星入侵者勾结，意图奴役{targetNationNameWithArticle}。这股舆论风暴已然甚嚣尘上，以至于{targetNationAdjective}政府官员感到压力，不得不作出回应。
TINarrativeEventTemplate.event_2003_PublicSpeculation.option0=就让他们猜去吧。
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionResult0=由于缺乏关于太空造访者的确切信息，{targetNationAdjective}的公众正在胡乱猜测。
TINarrativeEventTemplate.event_2003_PublicSpeculation.option1=禁止讨论该话题。
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionResult1=由于缺乏关于太空造访者的确切信息，{targetNationAdjective}的公众正在胡乱猜测。
TINarrativeEventTemplate.event_2003_PublicSpeculation.option2=公布目前掌握的少量信息，安抚民众。
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionResult2=由于缺乏关于太空造访者的确切信息，{targetNationAdjective}的公众正在胡乱猜测。
TINarrativeEventTemplate.event_2003_PublicSpeculation.option3=抛出我们自己的假说，主动搅局。
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionDetail3=<skip/>
TINarrativeEventTemplate.event_2003_PublicSpeculation.optionResult3=由于缺乏关于太空造访者的确切信息，{targetNationAdjective}的公众正在胡乱猜测。

TINarrativeEventTemplate.displayName.event_2003_ExecutiveDysfunction=行政失能
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.summary={targetNationAdjective}行政部门无法就外星人问题达成明确共识。
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.query=尽管我方阵营对{targetNationAdjective}政府的关键成员有一定影响力，但由于我方行动以及外星人降临事件均处于极高的机密状态，使得我们难以有力地阐明自己的立场。因此，政府内部的许多人认为外星人来到地球纯属骗局，而且认为还有许多更紧迫的本土问题值得他们关注，比如学校午餐的质量。
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.option0=让他们自己争论去吧。
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.optionResult0={summary}
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.option1=就让怀疑者去质疑吧。
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.optionDetail1=毕竟，人人都知道一顿优质午餐有多重要。
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.optionResult1={targetNationAdjective}当局决定优先提升学校午餐的质量。
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.option2=推动采取更果断的应对措施。
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_ExecutiveDysfunction.optionResult2={targetNationAdjective}当局敦促对外星人采取更果断的应对措施。

TINarrativeEventTemplate.displayName.event_2003_StrangeLights=神秘光芒
TINarrativeEventTemplate.event_2003_StrangeLights.summary=各大社交平台上已经彻底炸开了锅，大量照片和视频在网上疯传，据称拍到了{targetNationNameWithArticle}上空掠过的神秘亮光。
TINarrativeEventTemplate.event_2003_StrangeLights.query=自然，网友们对此众说纷纭：这亮光究竟是自然现象、人为制造，还是外星人所为？甚至有人质疑这些图片是否真实存在。
TINarrativeEventTemplate.event_2003_StrangeLights.option0=不过是沼气罢了。
TINarrativeEventTemplate.event_2003_StrangeLights.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_StrangeLights.optionResult0={targetNationNameWithArticleCap}声称天空中的亮光只是沼气。
TINarrativeEventTemplate.event_2003_StrangeLights.option1=派遣科学工作组，对这类现象进行正式调查。
TINarrativeEventTemplate.event_2003_StrangeLights.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_StrangeLights.optionResult1={targetNationNameWithArticleCap}派遣科学工作组，调查天空中的亮光。
TINarrativeEventTemplate.event_2003_StrangeLights.option2=派遣战斗机巡逻天空，展示武力威慑。
TINarrativeEventTemplate.event_2003_StrangeLights.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_StrangeLights.optionResult2={targetNationNameWithArticleCap}派遣战斗机拦截天空中的亮光。
TINarrativeEventTemplate.event_2003_StrangeLights.option3=鼓励追随者多去户外欣赏这些美丽的亮光。
TINarrativeEventTemplate.event_2003_StrangeLights.optionDetail3=<skip/>
TINarrativeEventTemplate.event_2003_StrangeLights.optionResult3={targetFactionNameCap}鼓励追随者多去户外活动。

TINarrativeEventTemplate.displayName.event_2003_LethargicTroops=士气低落的部队
TINarrativeEventTemplate.event_2003_LethargicTroops.summary={targetNationAdjective}武装部队的士气跌至历史最低点。
TINarrativeEventTemplate.event_2003_LethargicTroops.query=各军种的军官报告称，部队中缺勤、消极怠工问题频发，整体缺乏工作激情，不愿履行职责的现象急剧增多，令人担忧。问题已相当严重，即使实施严厉的纪律处分也收效甚微。被问及原因时，士兵们不愿具体解释，只是泛泛地表示自己认为战斗已毫无意义。
TINarrativeEventTemplate.event_2003_LethargicTroops.option0=为国效忠的誓言都抛之脑后了吗？
TINarrativeEventTemplate.event_2003_LethargicTroops.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_LethargicTroops.optionResult0={summary}
TINarrativeEventTemplate.event_2003_LethargicTroops.option1=增加部队福利的预算。
TINarrativeEventTemplate.event_2003_LethargicTroops.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_LethargicTroops.optionResult1={targetNationNameWithArticleCap}增加了部队福利的预算。
TINarrativeEventTemplate.event_2003_LethargicTroops.option2=肃清最大的麻烦制造者，以儆效尤。
TINarrativeEventTemplate.event_2003_LethargicTroops.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_LethargicTroops.optionResult2={targetNationNameWithArticleCap}肃清了军队中的麻烦制造者。
TINarrativeEventTemplate.event_2003_LethargicTroops.option3=调查是否存在外星势力暗中破坏的迹象。
TINarrativeEventTemplate.event_2003_LethargicTroops.optionDetail3=<skip/>
TINarrativeEventTemplate.event_2003_LethargicTroops.option3.outcome0=成功。
TINarrativeEventTemplate.event_2003_LethargicTroops.option3.outcome0.Summary={targetNationNameWithArticleCap}揭露了自家武装部队中存在外星人渗透的迹象。
TINarrativeEventTemplate.event_2003_LethargicTroops.option3.outcome0.Detail=我们成功在军队中发现了外星人渗透的证据！得益于此，不仅士气恢复到了以往水平，{targetNationAdjective}的武装部队如今也更有能力应对未来的外星人威胁。
TINarrativeEventTemplate.event_2003_LethargicTroops.option3.outcome1=失败。
TINarrativeEventTemplate.event_2003_LethargicTroops.option3.outcome1.Summary={targetNationNameWithArticleCap}将自家武装部队的士气低落状况归咎于外星人。
TINarrativeEventTemplate.event_2003_LethargicTroops.option3.outcome1.Detail=对外星人渗透的指控适得其反，反而加剧了士兵们的怨恨情绪。




//// SERVANTS EVENTS

TINarrativeEventTemplate.displayName.event_2003_CultofEquality=平等教派
TINarrativeEventTemplate.event_2003_CultofEquality.summary=一种新的宗教运动正在{targetNationNameWithArticleAndPlacePrep}迅速蔓延。
TINarrativeEventTemplate.event_2003_CultofEquality.query=传教人员和布道者正有组织地走访工厂、学校和社区中心，他们的主张在受众中引发了深远的共鸣。如今，每个朋友圈子里都至少有一个人认识该宗教运动的成员。与该运动相关的示威者和活动人士已开始出现在{targetRegionName}及其他城市的街头，行动展现出异乎寻常的协调性和一致性。<br/><br/>他们的主张是：人人生而平等，因此必须与邻里过上同等的生活。如果某些人拥有远超他人的物质财富，社会就会产生不和谐。那些囤积财富的人，是时候把一切归还给人类社会了。
TINarrativeEventTemplate.event_2003_CultofEquality.option0=让他们去奔走抗议吧。
TINarrativeEventTemplate.event_2003_CultofEquality.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_CultofEquality.optionResult0={summary}
TINarrativeEventTemplate.event_2003_CultofEquality.option1=顺应平等诉求，做出妥协。
TINarrativeEventTemplate.event_2003_CultofEquality.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_CultofEquality.optionResult1={actorNameWithArticleCap}向新兴宗教运动做出了让步。
TINarrativeEventTemplate.event_2003_CultofEquality.option2=镇压其渗透破坏活动。
TINarrativeEventTemplate.event_2003_CultofEquality.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_CultofEquality.optionResult2={actorNameWithArticleCap}对新兴宗教运动实施了镇压。
TINarrativeEventTemplate.event_2003_CultofEquality.option3=调查他们之中是否存在外星人介入的迹象。
TINarrativeEventTemplate.event_2003_CultofEquality.optionDetail3=<skip/>
TINarrativeEventTemplate.event_2003_CultofEquality.option3.outcome0=成功。
TINarrativeEventTemplate.event_2003_CultofEquality.option3.outcome0.Summary={actorNameWithArticleCap}揭露了某新兴宗教运动中存在外星人渗透的迹象。
TINarrativeEventTemplate.event_2003_CultofEquality.option3.outcome0.Detail=我们成功发现了外星势力暗中影响该运动的迹象！这使得该运动声名扫地，其大部分前成员均已散去，未再引发任何风波。
TINarrativeEventTemplate.event_2003_CultofEquality.option3.outcome1=失败。
TINarrativeEventTemplate.event_2003_CultofEquality.option3.outcome1.Summary={actorNameWithArticleCap}未能在新兴宗教运动中发现外星人渗透的迹象。
TINarrativeEventTemplate.event_2003_CultofEquality.option3.outcome1.Detail=对于外星人渗透的指控适得其反，加剧了社会的怨恨情绪。民众的回应是：如果追求平等就会被视为外星人，那么他们就是外星人。

TINarrativeEventTemplate.displayName.event_2003_CultofUnity=团结教派
TINarrativeEventTemplate.event_2003_CultofUnity.summary=一种新的宗教运动正在{targetNationNameWithArticleAndPlacePrep}迅速蔓延。
TINarrativeEventTemplate.event_2003_CultofUnity.query=传教人员和布道者正有组织地走访工厂、学校和社区中心，他们的主张在受众中引发了深远的共鸣。如今，每个朋友圈子里都至少有一个人认识该宗教运动的成员。与该运动相关的示威者和活动人士已开始出现在{targetRegionName}及其他城市的街头，行动展现出异乎寻常的协调性和一致性。<br/><br/>他们的主张是：即使这个世界充满动荡，日常生活也有很多烦恼，你也要始终记得关爱邻里。唯有如此，你才能学会爱自己。
TINarrativeEventTemplate.event_2003_CultofUnity.option0=这就是救世主对我们的期望。
TINarrativeEventTemplate.event_2003_CultofUnity.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_CultofUnity.optionResult0={summary}
TINarrativeEventTemplate.event_2003_CultofUnity.option1=救世主还有更伟大的计划。
TINarrativeEventTemplate.event_2003_CultofUnity.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_CultofUnity.optionResult1={summary}

TINarrativeEventTemplate.displayName.event_2003_CultofPeace=和平教派
TINarrativeEventTemplate.event_2003_CultofPeace.summary=一种新的宗教运动正在{targetNationNameWithArticleAndPlacePrep}迅速蔓延。
TINarrativeEventTemplate.event_2003_CultofPeace.query=传教人员和布道者正有组织地走访工厂、学校和社区中心，他们的主张在受众中引发了深远的共鸣。如今，每个朋友圈子里都至少有一个人认识该宗教运动的成员。与该运动相关的示威者和活动人士已开始出现在{targetRegionName}及其他城市的街头，行动展现出异乎寻常的协调性和一致性。<br/><br/>他们的主张是：世界日益加剧的军国主义只会带来痛苦与灾难。{targetNationNameWithArticleCap}具有全球领先的军工复合体和远征能力，在这个问题上比大多数国家负有更大的责任，因此必须立即阻止并扭转这一趋势，否则将无法避免即将到来的死亡与毁灭。
TINarrativeEventTemplate.event_2003_CultofPeace.option0=让他们去奔走抗议吧。
TINarrativeEventTemplate.event_2003_CultofPeace.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_CultofPeace.optionResult0={summary}
TINarrativeEventTemplate.event_2003_CultofPeace.option1=顺应裁军诉求，做出妥协。
TINarrativeEventTemplate.event_2003_CultofPeace.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_CultofPeace.optionResult1={actorNameWithArticleCap}向新兴宗教运动做出了让步。
TINarrativeEventTemplate.event_2003_CultofPeace.option2=镇压其渗透破坏活动。
TINarrativeEventTemplate.event_2003_CultofPeace.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_CultofPeace.optionResult2={actorNameWithArticleCap}对新兴宗教运动实施了镇压。
TINarrativeEventTemplate.event_2003_CultofPeace.option3=调查他们之中是否存在外星人介入的迹象。
TINarrativeEventTemplate.event_2003_CultofPeace.optionDetail3=<skip/>
TINarrativeEventTemplate.event_2003_CultofPeace.option3.outcome0=成功。
TINarrativeEventTemplate.event_2003_CultofPeace.option3.outcome0.Summary={actorNameWithArticleCap}揭露了某新兴宗教运动中存在外星人渗透的迹象。
TINarrativeEventTemplate.event_2003_CultofPeace.option3.outcome0.Detail=我们成功发现了外星势力暗中影响该运动的迹象！这使得该运动声名扫地，其大部分前成员均已散去，未再引发任何风波。
TINarrativeEventTemplate.event_2003_CultofPeace.option3.outcome1=失败。
TINarrativeEventTemplate.event_2003_CultofPeace.option3.outcome1.Summary={actorNameWithArticleCap}未能在新兴宗教运动中发现外星人渗透的迹象。
TINarrativeEventTemplate.event_2003_CultofPeace.option3.outcome1.Detail=对于外星人渗透的指控适得其反，加剧了社会的怨恨情绪。民众的回应是：如果追求和平就会被视为外星人，那么他们就是外星人。

TINarrativeEventTemplate.displayName.event_2003_CultofAction=实干教派
TINarrativeEventTemplate.event_2003_CultofAction.summary=一种新的宗教运动正在{targetNationNameWithArticleAndPlacePrep}迅速蔓延。
TINarrativeEventTemplate.event_2003_CultofAction.query=传教人员和布道者正有组织地走访工厂、学校和社区中心，他们的主张在受众中引发了深远的共鸣。如今，每个朋友圈子里都至少有一个人认识该宗教运动的成员。与该运动相关的示威者和活动人士已开始出现在{targetRegionName}及其他城市的街头，行动展现出异乎寻常的协调性和一致性。<br/><br/>他们的主张是：人人都知道这个世界扭曲而腐朽，但仅仅知晓这一点是不够的。言语无法改变世界，唯有实干才能做到。必须有人迈出第一步去创造一个更美好的世界，而那个人就是你。
TINarrativeEventTemplate.event_2003_CultofAction.option0=这就是救世主对我们的期望。
TINarrativeEventTemplate.event_2003_CultofAction.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_CultofAction.optionResult0={summary}
TINarrativeEventTemplate.event_2003_CultofAction.option1=救世主还有更伟大的计划。
TINarrativeEventTemplate.event_2003_CultofAction.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_CultofAction.optionResult1={summary}

TINarrativeEventTemplate.displayName.event_2003_CultofArmageddon=审判教派
TINarrativeEventTemplate.event_2003_CultofArmageddon.summary=一种新的宗教运动正在{targetNationNameWithArticleAndPlacePrep}迅速蔓延。
TINarrativeEventTemplate.event_2003_CultofArmageddon.query=传教人员和布道者正有组织地走访工厂、学校和社区中心，他们的主张在受众中引发了深远的共鸣。如今，每个朋友圈子里都至少有一个人认识该宗教运动的成员。与该运动相关的示威者和活动人士已开始出现在{targetRegionName}及其他城市的街头，行动展现出异乎寻常的协调性和一致性。<br/><br/>他们的主张是：核武器是人类对世界的诅咒。只要还存在一枚核弹头，走向毁灭的倒计时就永远不会停止。相互确保毁灭，世界就一定会毁灭：如果一个国家不能以身作则，其他国家又凭什么效仿？
TINarrativeEventTemplate.event_2003_CultofArmageddon.option0=让他们去奔走抗议吧。
TINarrativeEventTemplate.event_2003_CultofArmageddon.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_CultofArmageddon.optionResult0={summary}
TINarrativeEventTemplate.event_2003_CultofArmageddon.option1=顺应控核诉求，做出妥协。
TINarrativeEventTemplate.event_2003_CultofArmageddon.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_CultofArmageddon.optionResult1={actorNameWithArticleCap}向新兴宗教运动做出了让步。
TINarrativeEventTemplate.event_2003_CultofArmageddon.option2=镇压其渗透破坏活动。
TINarrativeEventTemplate.event_2003_CultofArmageddon.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_CultofArmageddon.optionResult2={actorNameWithArticleCap}对新兴宗教运动实施了镇压。
TINarrativeEventTemplate.event_2003_CultofArmageddon.option3=调查他们之中是否存在外星人介入的迹象。
TINarrativeEventTemplate.event_2003_CultofArmageddon.optionDetail3=<skip/>
TINarrativeEventTemplate.event_2003_CultofArmageddon.option3.outcome0=成功。
TINarrativeEventTemplate.event_2003_CultofArmageddon.option3.outcome0.Summary={actorNameWithArticleCap}揭露了某新兴宗教运动中存在外星人渗透的迹象。
TINarrativeEventTemplate.event_2003_CultofArmageddon.option3.outcome0.Detail=我们成功发现了外星势力暗中影响该运动的迹象！这使得该运动声名扫地，其大部分前成员均已散去，未再引发任何风波。
TINarrativeEventTemplate.event_2003_CultofArmageddon.option3.outcome1=失败。
TINarrativeEventTemplate.event_2003_CultofArmageddon.option3.outcome1.Summary={actorNameWithArticleCap}未能在新兴宗教运动中发现外星人渗透的迹象。
TINarrativeEventTemplate.event_2003_CultofArmageddon.option3.outcome1.Detail=对于外星人渗透的指控适得其反，加剧了社会的怨恨情绪。民众的回应是：如果追求和平就会被视为外星人，那么他们就是外星人。




// TRANSLATION BATCH 2
TINarrativeEventTemplate.displayName.event_2003_InsightfulBlogger=颇具洞察力的博主
TINarrativeEventTemplate.event_2003_InsightfulBlogger.summary=我方的一名通讯人员声称，在社交媒体上发现了极其重要的情报。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.query=该名人员在履行公职、密切监视全球通信网络时，偶然发现了一篇博客，作者自称已获得外星人在地球上活动的证据。通常情况下，此类说法会被直接驳回，但如今我们所处的时代并不寻常，而且，博客附带的证据也出人意料地很有说服力。或许此人掌握着我们目前还不知道的情况——既然我们能在网络上找到这些证据，其他人也一定会发现。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option0=我们没时间搭理这些虚假消息。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.optionDetail0=<skip/>
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option0.outcome0=什么事情都没发生。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option0.outcome0.Summary=关于外星人活动的证据正在社交媒体上传播。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option0.outcome0.Detail=什么事情都没发生。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option0.outcome1=???
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option0.outcome1.Summary=关于外星人活动的证据正在社交媒体上传播。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option0.outcome1.Detail=<skip/>
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1=去拜访一下这个人。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.optionDetail1=<skip/>
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome0=成功。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome0.Summary=关于外星人活动的证据正在社交媒体上传播。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome0.Detail=我方特工到达了博主的住所，受邀入内进行了友好的交谈。双方边喝咖啡边聊，博主主动拿出了一些照片，上面清楚地显示了该地区存在外星人活动的迹象，还拿出几件具有特殊化学成分的物品。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome1=错过。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome1.Summary=关于外星人活动的证据正在社交媒体上传播。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome1.Detail=我方特工到达了博主的住所，发现房子完全空无一人。虽然有近期居住过的痕迹，但这里没有住户，也没有电脑设备。特工询问了邻居，他们表示很久以来一直没见到有谁住在那里。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome2=诈骗。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome2.Summary=关于外星人活动的证据正在社交媒体上传播。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option1.outcome2.Detail=我方特工到达了博主的住所，很快就发现，那些在网传照片中看起来很唬人的东西完全是伪造的。所谓外星航天器的残骸，不过是一些涂了颜色的泡沫道具。随后，该博主又拿我们的到访当做证据，声称自己已经“离真相非常近”。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.option2=扩大传播，让更多人知道这些消息。
TINarrativeEventTemplate.event_2003_InsightfulBlogger.optionDetail2=<skip/>
TINarrativeEventTemplate.event_2003_InsightfulBlogger.optionResult2=关于外星人活动的证据正在社交媒体上传播。