
// Dark Skies DLC

TIProjectTemplate.displayName.Project_BS_ExploringOurOptions=探索更多的选择
TIProjectTemplate.summary.Project_BS_ExploringOurOptions=我们要为当前最紧迫的问题寻找短期解决方案。 
TIProjectTemplate.description.Project_BS_ExploringOurOptions=无论外星人的目标是什么，他们似乎更喜欢用有条不紊的方式悄然推进。然而，世界已经改变，我们不能再坐以待毙，指望科技的自然进步来满足眼下的急切需要。我们的科学家和工程师已经开始探索现有技术的新应用，预计很快就能实现一些令人振奋的新项目。此外，我们的研究人员还发现了一些唾手可得的成果，可以立即投入使用。

TIProjectTemplate.displayName.Project_BS_ResearchRepairProjectA=研究经费：计算
TIProjectTemplate.summary.Project_BS_ResearchRepairProjectA=我们获得了计算领域的研究经费。
//TIProjectTemplate.description.Project_BS_ResearchRepairProjectA=针对计算机科学领域的定向资金投入，显著提高了整体科研进展速度，推动了该领域的技术突破。

TIProjectTemplate.displayName.Project_BS_ResearchRepairProjectB=研究经费：通信
TIProjectTemplate.summary.Project_BS_ResearchRepairProjectB=我们获得了通信领域的研究经费。
//TIProjectTemplate.description.Project_BS_ResearchRepairProjectB=增加通信研究经费，促使科研进步加快，而且在方法、设备和研究效率方面实现了显著提升。

TIProjectTemplate.displayName.Project_BS_ResearchRepairProjectC=研究经费：航天
TIProjectTemplate.summary.Project_BS_ResearchRepairProjectC=我们获得了航天领域的研究经费。 
//TIProjectTemplate.description.Project_BS_ResearchRepairProjectC=增加航空航天与天文学领域的研究经费，加快了科学进步速度，提高了太空研究领域的效率。

TIProjectTemplate.displayName.Project_BS_ResearchRepairProjectD=研究经费：防御
TIProjectTemplate.summary.Project_BS_ResearchRepairProjectD=我们获得了防御领域的研究经费。
//TIProjectTemplate.description.Project_BS_ResearchRepairProjectD=我们增加了对科学团体的资金投入，鼓励其将近期突破性成果应用到军事领域，显著加快了科学进步的步伐。

TIProjectTemplate.displayName.Project_BS_SafeguardtheLandI=守护大地 I
TIProjectTemplate.summary.Project_BS_SafeguardtheLandI=我们需要制定短期方案，保障地球上的利益。
TIProjectTemplate.description.Project_BS_SafeguardtheLandI=外星人对地球的计划曝光后，在我方组织内部引发了巨大震动。我们已经尽可能采取了应对措施。研究人员还发现了一些全新的研究方向，可能会在即将到来的动荡时期为我们提供帮助。

TIProjectTemplate.displayName.Project_BS_SafeguardtheLandII=守护大地 II
TIProjectTemplate.summary.Project_BS_SafeguardtheLandII=我们有了更多的陆地军事短期方案。
TIProjectTemplate.description.Project_BS_SafeguardtheLandII=我们要持续备战，应对外星军事力量入侵地球。 

TIProjectTemplate.displayName.Project_BS_SafeguardtheLandIII=守护大地 III
TIProjectTemplate.summary.Project_BS_SafeguardtheLandIII=我们不再探索新的陆地军事计划。  
TIProjectTemplate.description.Project_BS_SafeguardtheLandIII=我们的短期准备方案已达到极限，想要取得任何进展都需要更多的基础科学突破。 

TIProjectTemplate.displayName.Project_BS_SafeguardtheSkyI=守护苍穹 I
TIProjectTemplate.summary.Project_BS_SafeguardtheSkyI=我们需要制定短期方案，保障太空中的利益。
TIProjectTemplate.description.Project_BS_SafeguardtheSkyI=外星人已将军事飞行器驶入我们的太阳系。那些畏惧其意图的人会感到自危，而那些不畏惧的人，也同样需要保护自己免受其他人的伤害。我们已竭尽所能，做好准备，适应太阳系的新常态，防范威胁。 

TIProjectTemplate.displayName.Project_BS_SafeguardtheSkyII=守护苍穹 II
TIProjectTemplate.summary.Project_BS_SafeguardtheSkyII=我们不再探索新的太空军事计划。  
TIProjectTemplate.description.Project_BS_SafeguardtheSkyII=面对太空军事化，我们做好了进一步的准备。目前，我们的短期准备方案已达到极限，想要取得任何进展都需要更多的基础科学突破。 

TIProjectTemplate.displayName.Project_BS_MakingHistoryI=创造历史：美洲
TIProjectTemplate.summary.Project_BS_MakingHistoryI=我们要在美洲地缘政治中探索新的可能。
//TIProjectTemplate.description.Project_BS_MakingHistoryI=在这样一个非常时期，我们之中一些更有野心的分析者认为，美洲存在可利用的社会政治切入点，只要符合我方利益，就能展开行动。

TIProjectTemplate.displayName.Project_BS_MakingHistoryII=创造历史：大洋洲
TIProjectTemplate.summary.Project_BS_MakingHistoryII=我们要在大洋洲地缘政治中探索新的可能。
//TIProjectTemplate.description.Project_BS_MakingHistoryII=在这样一个非常时期，我们之中一些更有野心的分析者认为，大洋洲存在可利用的社会政治切入点，只要符合我方利益，就能展开行动。

TIProjectTemplate.displayName.Project_BS_MakingHistoryIII=创造历史：中亚
TIProjectTemplate.summary.Project_BS_MakingHistoryIII=我们要在中亚地缘政治中探索新的可能。
//TIProjectTemplate.description.Project_BS_MakingHistoryIII=在这样一个非常时期，我们之中一些更有野心的分析者认为，中亚存在可利用的社会政治切入点，只要符合我方利益，就能展开行动。

TIProjectTemplate.displayName.Project_BS_MakingHistoryIV=创造历史：中东 
TIProjectTemplate.summary.Project_BS_MakingHistoryIV=我们要在中东地缘政治中探索新的可能。
//TIProjectTemplate.description.Project_BS_MakingHistoryIV=在这样一个非常时期，我们之中一些更有野心的分析者认为，中东存在可利用的社会政治切入点，只要符合我方利益，就能展开行动。

TIProjectTemplate.displayName.Project_BS_MakingHistoryV=创造历史：欧洲
TIProjectTemplate.summary.Project_BS_MakingHistoryV=我们要在欧洲地缘政治中探索新的可能。
//TIProjectTemplate.description.Project_BS_MakingHistoryV=在这样一个非常时期，我们之中一些更有野心的分析者认为，欧洲存在可利用的社会政治切入点，只要符合我方利益，就能展开行动。

TIProjectTemplate.displayName.Project_BS_MakingHistoryVI=创造历史：非洲
TIProjectTemplate.summary.Project_BS_MakingHistoryVI=我们要在非洲地缘政治中探索新的可能。
//TIProjectTemplate.description.Project_BS_MakingHistoryVI=在这样一个非常时期，我们之中一些更有野心的分析者认为，非洲存在可利用的社会政治切入点，只要符合我方利益，就能展开行动。

TIProjectTemplate.displayName.Project_BS_MakingHistoryVII=创造历史：东南亚
TIProjectTemplate.summary.Project_BS_MakingHistoryVII=我们要在东南亚地缘政治中探索新的可能。
//TIProjectTemplate.description.Project_BS_MakingHistoryVII=在这样一个非常时期，我们之中一些更有野心的分析者认为，东南亚存在可利用的社会政治切入点，只要符合我方利益，就能展开行动。

TIProjectTemplate.displayName.Project_BS_UnityThroughStrength=诉诸武力
TIProjectTemplate.summary.Project_BS_UnityThroughStrength=我们要运用军事实力保障自身利益。 
TIProjectTemplate.description.Project_BS_UnityThroughStrength=力量当然是地缘政治工具箱中最明显的手段，同时也非常有效。研究人员已开发出更先进的工具和方法，可以从与我们有利益关系的国家身上充分挖掘军事潜力。 

TIProjectTemplate.displayName.Project_BS_RootingOutCorruption=根除自身腐败
TIProjectTemplate.summary.Project_BS_RootingOutCorruption=我们要改善本国的治理水平。
TIProjectTemplate.description.Project_BS_RootingOutCorruption=迄今为止，为了争取关键个人和组织的支持，我们还容忍着一定程度的贪腐，但是，这种狭隘的利益已成为实现目标的障碍。我们已制定了具体计划，削弱这些势力的影响，必要时也可以彻底将其清除。

TIProjectTemplate.displayName.Project_BS_SecuringOurInterests=新的秩序
TIProjectTemplate.summary.Project_BS_SecuringOurInterests=我们要稳定各国局势，提升其生产力。 
TIProjectTemplate.description.Project_BS_SecuringOurInterests=为了走到今天这一步，我们解除了许多制约机制。而如今，我们却希望重新建立这些机制，巩固自己对权力的掌控。此外，我们与各方势力引发的巨大变革，已在集体心理上留下深刻印记——这种人心惶惶的局面，正在悄然扼杀我们的发展潜力。为此，我们已开始推行一系列改革措施，旨在保护执行机构并重建信任。

TIProjectTemplate.displayName.Project_BS_ProprietarySpaceResearchI=专有太空研究：资源
TIProjectTemplate.summary.Project_BS_ProprietarySpaceResearchI=我们要确定如何利用现有科技从小行星中提取资源。 
TIProjectTemplate.description.Project_BS_ProprietarySpaceResearchI=今后，人类需要学会利用太空中的丰富资源，这似乎已成定局。然而，我们目前仍缺乏实现这一目标所需的许多基础技术。不过，我们的研究人员认为，有一些可行方案可以在短期内开始积累资源，尽管规模有限，产量也较低。我们已经可以从附近的小行星开采资源，但其他开采目标仍面临着尚未解决的独特工程挑战。

TIProjectTemplate.displayName.Project_BS_ProprietarySpaceResearchII=专有太空研究：空间站
TIProjectTemplate.summary.Project_BS_ProprietarySpaceResearchII=我们要确定如何利用现有科技建造更大的空间站。 
TIProjectTemplate.description.Project_BS_ProprietarySpaceResearchII=理论上，建造大型空间站主要取决于资源和人力，但在实践中仍然存在很多别的问题，而解决这些问题所需要的技术要么尚不成熟，要么完全处于理论阶段。不过，我们的研究人员已提出一些创新性解决方案，有望推动空间站扩建。但是需要等待更多的基础研究完成，目前我们只能建设规模较小、人口较少的太空殖民地舱体。 

TIProjectTemplate.displayName.Project_BS_ProprietarySpaceResearchIII=专有太空研究：轨道实验室
TIProjectTemplate.summary.Project_BS_ProprietarySpaceResearchIII=我们利用规模更大的空间站和太空基础设施，建造先进的轨道实验室。 
TIProjectTemplate.description.Project_BS_ProprietarySpaceResearchIII=我们已取得诸多成就，但是要进一步发展，就必须提升研究能力。为此，我们的科学家和工程师提出了一些有望改进太空研究实验室的方案。  

