
// Dark Skies DLC


//// RECOVERY EVENTS

TINarrativeEventTemplate.displayName.event_PostApoc_OldWorldBooks=旧世界书籍
TINarrativeEventTemplate.event_PostApoc_OldWorldBooks.summary=战争结束后，许多社区因居民仓促撤离而沦为废墟。重建人员在清理这些荒废街区时，意外发现了一批藏匿于此的旧日书籍。
TINarrativeEventTemplate.event_PostApoc_OldWorldBooks.query=这批藏书包括在战争爆发前很久就写成的经典文学作品、理工科与社会科学的大学教材，甚至还有几册曾经风靡一时、长期连载的漫画系列。这些书籍有助于恢复{targetNationNameWithPrep}的教育体系。
TINarrativeEventTemplate.event_PostApoc_OldWorldBooks.option0=我们还是需要从过去学习很多东西。
TINarrativeEventTemplate.event_PostApoc_OldWorldBooks.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_OldWorldBooks.optionResult0={targetNationNameWithArticleAndPlacePrep}的重建人员发现了一批旧日书籍。

TINarrativeEventTemplate.displayName.event_PostApoc_OldWorldDoctrines=旧世界战术
TINarrativeEventTemplate.event_PostApoc_OldWorldDoctrines.summary=战后大批被炸毁的城市与要塞皆被废弃。重建人员在清理这些废墟时，发现了一处隐藏的掩体设施。
TINarrativeEventTemplate.event_PostApoc_OldWorldDoctrines.query=距离战争结束已过去许久，幸存者早已离开，武器和补给品也早已生锈或腐烂。然而，我们在底下的一层找到了一批作战手册和战争计划，详细阐述了军队在战争时期奉行的战略学说。这些资料可以大大提升{targetNationNameWithArticle}对战争的理解。
TINarrativeEventTemplate.event_PostApoc_OldWorldDoctrines.option0=向前人学习这些内容，真的是一件好事吗？
TINarrativeEventTemplate.event_PostApoc_OldWorldDoctrines.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_OldWorldDoctrines.optionResult0={targetNationNameWithArticleAndPlacePrep}的重建人员发现了一处隐藏的掩体设施。

TINarrativeEventTemplate.displayName.event_PostApoc_OldWorldMedia=旧世界媒介
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.summary=战争结束后，许多社区因居民仓促撤离而沦为废墟。重建人员在清理这些荒废街区时，意外发现了一批藏匿于此的旧电影和音乐。
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.query=如今，工程师们可以相对容易地复刻这些媒介的录制与播放技术，但在修复过程中必须格外小心，以免磁带和唱片进一步受损。不过，等到完成清理，将其重制为当代设备格式后，相信观众会对战前人们喜爱的电影和音乐类型充满好奇。
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.option0=向全世界公开发布。
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.optionResult0={targetNationNameWithArticleAndPlacePrep}的重建人员发现了一批旧电影和音乐。
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.option1=将其留在{targetNationNameWithArticleAndPlacePrep}，开放专属收费观赏渠道。
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_OldWorldMedia.optionResult1={targetNationNameWithArticleAndPlacePrep}的重建人员发现了一批旧电影和音乐。

TINarrativeEventTemplate.displayName.event_PostApoc_MemorialtotheFallen=烈士纪念日
TINarrativeEventTemplate.event_PostApoc_MemorialtotheFallen.summary=来自{targetNationNameWithArticle}各地的民众齐聚一堂，共同悼念逝去的英烈，举行五年一度的纪念活动。
TINarrativeEventTemplate.event_PostApoc_MemorialtotheFallen.query=政府官员、牧师和公众代表轮流发言，宣读了 1962 年核灾难中遇难者的姓名。仪式庄重而乏味，却在后末日时代起到了重要的作用，让民众始终铭记历史。即使世界翻开了新的篇章，人们仍然不会忘记核武器曾带来的广泛破坏，立誓永不重蹈覆辙。
TINarrativeEventTemplate.event_PostApoc_MemorialtotheFallen.option0=永远铭记。
TINarrativeEventTemplate.event_PostApoc_MemorialtotheFallen.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_MemorialtotheFallen.optionResult0={summary}



TINarrativeEventTemplate.displayName.event_PostApoc_UnauthorizedSalvage=非法回收	
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.summary={targetRegionName}周边的废墟区域正在进行未经授权的回收行动。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.query=很不巧，由于这些地区尚未完全处于{targetNationAdjective}合法机构的控制之下，一些投机者就趁机擅自搜寻战争时期的遗存物品。这种现象不仅催生了一个蓬勃发展的黑市，严重阻碍了{targetNationNameWithArticle}的经济复苏，还加剧了他们与当地幸存社区之间的紧张关系。这些社区的民众虽然稀少，却还在战乱废墟中艰难求生，而且坚称对这片土地上的资产享有所有权。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0=这已超出我们的控制。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome0=继续回收作业。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome0.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome1=回收人员发现了旧日书籍。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome1.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome2=回收人员发现了旧日掩体。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome2.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome2.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome3=回收人员发现了旧日媒介。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome3.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option0.outcome3.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option1=严厉打击这种非法行为。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.optionResult1={targetNationNameWithArticleCap}严厉打击{targetRegionNameSentIn}未经授权的回收作业。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2=对获得授权的回收作业发放奖励。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome0=继续回收作业。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome0.Summary={targetRegionName}周边的废墟区域正在进行经过授权的回收行动。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome0.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome1=回收人员发现了旧日书籍。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome1.Summary={targetRegionName}周边的废墟区域正在进行经过授权的回收行动。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome1.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome2=回收人员发现了旧日掩体。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome2.Summary={targetRegionName}周边的废墟区域正在进行经过授权的回收行动。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome2.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome3=回收人员发现了旧日媒介。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome3.Summary={targetRegionName}周边的废墟区域正在进行经过授权的回收行动。
TINarrativeEventTemplate.event_PostApoc_UnauthorizedSalvage.option2.outcome3.Detail=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_ArmedProcession=武装游行
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.summary=许多人排成一列，有男有女，手持步枪，高喊口号，在{targetRegionName}游行。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.query=这场游行并不是针对{targetNationAdjective}政府的抗议或叛乱，而是一场情感宣泄，控诉战争给{targetNationNameWithArticle}带来的死亡阴霾，以及表达{targetNationAdjective}民众的求生意志。据说，游行这项活动起源于战后混乱时期，起初是地方民兵自发组织的集会，此后逐渐成为{targetNationAdjective}文化中反复出现的元素。<br/><br/>然而，仍有一些政府成员担忧，如此多的武装人员聚集在一处，极易引发走私和其他犯罪活动。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option0={targetNationNameWithArticleCap}发生了歌颂生命的游行！
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option0.outcome0=一切皆好。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option0.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option0.outcome0.Detail=谢天谢地，这些担忧毫无根据。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option0.outcome1=发生了颠覆事件。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option0.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option0.outcome1.Detail=这些担忧可能也有道理。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option1=出于安全考虑，命令他们散去。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.optionResult1={summary}
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.option2=派几个便衣特工，暗中观察情况。
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_ArmedProcession.optionResult2={summary}

TINarrativeEventTemplate.displayName.event_PostApoc_OldWorldSatellite=旧世界卫星
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.summary=首批进入太空的宇航员发现了一颗战前遗留下来的旧卫星，至今仍在地球轨道上运行。
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.query=人类首次探索外太空的尝试极为短暂，仅持续了短短数年，寒冬战争就终结了当时所有人类的雄心壮志。或许，这种情况在无意识中导致一些人对太空产生了某种恐惧，让他们认为，人类若胆敢向苍穹伸手，就会再次招来天降灾祸。<br/><br/>正因如此，加之更多实际原因，人类几乎再也没有向太空计划投入任何资源。<br/><br/>但时代已然改变。外星人的到来证明了宇宙并非空无一物，而是真实存在着智慧生命。对许多人而言，宇宙依然是恐惧的来源；但如今这种恐惧已不再是抽象的概念，而是一种切实可感、能够直面并克服的威胁。<br/><br/>出乎意料的是，尽管几率渺茫，这个来自战前地球的微小遗物竟已存活了超过一个世纪，就像我们人类本身。虽然它早已无法运作，却依然矗立，纪念人类的勇气与坚韧。
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.option0=我们仍然可以从它的设计中学到一些东西。
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.optionResult0={targetFactionNameCap}回收了一颗环绕地球运行的战前旧卫星。
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.option1=应该放在博物馆里！
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.optionResult1={targetFactionNameCap}回收了一颗环绕地球运行的战前旧卫星。
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.option2=宇航员站在前人的肩膀上。
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_OldWorldSatellite.optionResult2={targetFactionNameCap}回收了一颗环绕地球运行的战前旧卫星。

TINarrativeEventTemplate.displayName.event_PostApoc_MuseumtotheOldWorld=旧世界博物馆
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.summary=理事提议建造一座博物馆，展出战前的遗物。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.query=目前，我们已经收集到了足够的遗物，完全可以捐赠其中一部分，用于存档和公众参观。根据预计，场馆的建设和管理相对简单，无需我们直接参与。剩下的问题只是确定博物馆的整体主题：这是一次独特的机会，让我们能够通过符合自身愿景的视角，重新塑造公众对寒冬战争的记忆。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.option0=文明建立在科学之上。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionResult0={targetFactionNameCap}建造了一座博物馆，展示战前的科学成果。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.option1=他们的生活方式令人钦佩。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionResult1={targetFactionNameCap}建造了一座博物馆，展示战前的生活方式。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.option2=他们的军事实力无与伦比。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionResult2={targetFactionNameCap}建造了一座博物馆，展示战前的军事实力。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.option3=他们的生活水平无与伦比。
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionDetail3=<skip/>
TINarrativeEventTemplate.event_PostApoc_MuseumtotheOldWorld.optionResult3={targetFactionNameCap}建造了一座博物馆，展示战前的生活标准。

//// NUKE EVENTS

TINarrativeEventTemplate.displayName.event_PostApoc_Anti-NuclearPublicity=反核宣传
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.summary={targetNationAdjective}公众公开强烈反对{targetNationNameWithPrep}拥有核武器。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.query=如今，核武器这一概念已被视为高度禁忌。在过去的一个世纪中，人们逐渐形成了共识：正是核武器的肆意发展与扩散导致了寒冬战争，因此绝不能再制造更多核武器，否则人类这一技术文明的持续生存就会面临更大威胁。即使是今天，外星人的到来颠覆了人们对世界的原有认知，激发了人们对安全的渴望，公众依然对核战争有着根深蒂固的恐惧，这很合理。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option0=他们的忧虑也在情理之中。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.optionResult0={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option1=敌人正在发展武器，我们别无选择！
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option1.outcome0=安抚。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option1.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option1.outcome0.Detail=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option1.outcome1=镇压。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option1.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearPublicity.option1.outcome1.Detail=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_Anti-NuclearActivism=反核抗议活动
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.summary=示威者冲击了曾参与{targetNationNameWithPrep}核计划的工厂和实验室。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.query=激进分子的暴力行动令{targetNationAdjective}安全部队措手不及。目前，尽管{targetNationNameWithPrep}的核威慑力量目前尚且安全，但高度敏感的设备和关键人员仍面临风险，可能会危及核计划的未来。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.option0=优先疏散人员。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.optionResult0={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.option1=优先疏散设备。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.optionResult1={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.option2=派出军队，驱散抗议者。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearActivism.optionResult2={summary}

TINarrativeEventTemplate.displayName.event_PostApoc_Anti-NuclearSabotage=反核破坏行动
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.summary=我们对{targetNationNameWithPrep}的核武库进行了一次突击检查，发现大量核弹头已无法使用。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.query=安全部队已逮捕在过去一年内可能接触过这些核弹头的所有工程师，以及此前负责提交虚假战备报告的检查人员，并且开始了审讯。截至目前，尚未有人开口供述，但整个团队士气普遍低迷。<br/><br/>唯一值得庆幸的是，目前没有迹象显示有任何核材料被转移出基地。显然，实施这一行为的人并不希望核武器的威胁扩散。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.option0=在核战争中，没有圣母的容身之地。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.optionResult0={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.option1=我们早有预料。真正的弹头在另一个设施里。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.optionDetail1=什么事情都没发生。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.optionResult1={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.option2=这次破坏行动很业余，我们的专家可以轻松修复。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.optionDetail2=什么事情都没发生。
TINarrativeEventTemplate.event_PostApoc_Anti-NuclearSabotage.optionResult2={summary}

TINarrativeEventTemplate.displayName.event_PostApoc_ScientistsProtestNuclearProgram=科学家抗议核计划
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.summary=顶尖科学家正在以辞职的方式抗议{targetNationNameWithPrep}的核计划。
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.query=这些科学家向政府发送了一封联名信，在其中声明，他们有责任确保科技仅用于人类和平发展，而非沦为战争与杀戮的工具，即使在极端情况下也不例外。他们在信中引用了 J·罗伯特·奥本海默的话，这位“原子弹之父”曾经也尝试过阻止自己的科学结晶毁灭世界，却终究徒劳无功。
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.option0=也许我们应该听从他们的警告。
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.optionResult0={summary}
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.option1=我们不需要那些爱哭鬼。
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.optionResult1={summary}
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.option2=不要让科学家涉足国家安全事务。
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_ScientistsProtestNuclearProgram.optionResult2={summary}




//// FACTION EVENTS (TRANSLATION BATCH 2)



TINarrativeEventTemplate.displayName.event_PostApoc_FactionPonderResist=在《疮痍大地》中顽强抵抗
TINarrativeEventTemplate.event_PostApoc_FactionPonderResist.summary=我们的世界刚刚走出寒冬战争的阴影，外星人就降临了，这一切意味着什么？
TINarrativeEventTemplate.event_PostApoc_FactionPonderResist.query=毫无疑问，在历史的长河中，这场战争是人类遭受的最严重的灾难——更令人痛心的是，这一切完全是人类咎由自取。一个多世纪以来，我们一直生活在核弹之火投下的阴影中，蜷缩着撑过漫长的寒冷，忍受恐惧与绝望。直到现在，度过多年的黑暗之后，希望的第一缕曙光才终于开始显现。一百年来，我们这个物种第一次可以重新相信未来。<br/><br/>但是，外星人降临了这个世界。它们原本可以向我们伸出友谊之手，凭借自己的先进科技，主动提出帮助我们重建家园。诚然，这种援助绝不会是无偿的：我们可不会那么天真，我们很清楚实力悬殊的文明相遇，往往会以怎样的方式收场。但即便如此，友善的态度也会带来慰藉，证明宇宙中并非只有我们在孤独地承受苦难。然而，它们却选择入侵并征服我们的星球。它们看到我们人类已经破碎不堪、跌入谷底，就决定利用我们的软弱。<br/><br/>那就这样吧。它们的行为早已说明了一切。我们不能再自欺欺人，而是要认清它们对人类的真实意图。如果我们想要生存，想要重建这个破碎的世界，就必须为这个目标而战。
TINarrativeEventTemplate.event_PostApoc_FactionPonderResist.option0=那么，我们一定会奋起抗争。
TINarrativeEventTemplate.event_PostApoc_FactionPonderResist.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_FactionPonderResist.optionResult0=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_FactionPonderDestroy=在《疮痍大地》中摧毁一切
TINarrativeEventTemplate.event_PostApoc_FactionPonderDestroy.summary=我们的世界刚刚走出寒冬战争的阴影，外星人就降临了，这一切意味着什么？
TINarrativeEventTemplate.event_PostApoc_FactionPonderDestroy.query=曾经，战争爆发的原因常常是争夺物质，甚至是平淡无奇的琐事：国王与表亲之间的私人恩怨；凭借一份五十年前的产权文件，争夺某一小块土地的所有权；或是嫉妒邻居的资源与繁荣。一般而言，战争都是职业军人之间的搏杀，无论胜负，大多数平常人的生活依旧还会继续。<br/><br/>随着科技的进步和人类视野的不断拓展，战争的规模也随之扩大。战争的起因不再仅仅是资源或自尊，而是关乎整个物种的未来。两次世界大战无异于一场全面动员，旨在消灭敌对文明，决定人类历史的走向。到了寒冬战争时期，战争已经将全人类都卷了进来，几乎要将人类彻底抹去。<br/><br/>如今，人类的视野再次扩展。随着外星人的到来，战场不仅在我们的星球上，而且延伸到了宇宙深处。这场关乎生存的宏大战争，最终只能有一个胜利者。
TINarrativeEventTemplate.event_PostApoc_FactionPonderDestroy.option0=最后的胜利者一定会是我们。
TINarrativeEventTemplate.event_PostApoc_FactionPonderDestroy.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_FactionPonderDestroy.optionResult0=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_FactionPonderExploit=在《疮痍大地》中投机谋利
TINarrativeEventTemplate.event_PostApoc_FactionPonderExploit.summary=我们的世界刚刚走出寒冬战争的阴影，外星人就降临了，这一切意味着什么？
TINarrativeEventTemplate.event_PostApoc_FactionPonderExploit.query=在象牙塔里的某些学者眼中、在政客向平民大众的宣传中，人类历史是一条笔直向前的进程。但是，事实恰恰相反，人类历史是一个不断起伏的循环，每一次高峰与低谷都各自伴随着危险与机遇。真正掌控世界的人，正是懂得识别这种规律，拿出同等规模的雄心，利用每一次上升与衰退的人。<br/><br/>因此，对我们而言，寒冬战争本身并无特别之处。失败者死去，胜利者获利——这正是世界一贯的运行法则。<br/><br/>如果不是外星人降临，我们本来可以从战后的繁荣时期继续获益长达百年，收割这场战后春天的果实。<br/><br/>诚然，这一次下行周期来得实在太早，远远超出了所有人的预计。有一些人失去了财富，甚至失去了生命。但我们是幸存者，他们的损失就是我们的收获。与来自星辰的新物种竞争，固然会带来新的危险，但也创造了全新的机遇。
TINarrativeEventTemplate.event_PostApoc_FactionPonderExploit.option0=那么，我们当中谁有胆量赚这一笔呢？
TINarrativeEventTemplate.event_PostApoc_FactionPonderExploit.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_FactionPonderExploit.optionResult0=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_FactionPonderSubmit=在《疮痍大地》中接纳降临
TINarrativeEventTemplate.event_PostApoc_FactionPonderSubmit.summary=我们的世界刚刚走出寒冬战争的阴影，外星人就降临了，这一切意味着什么？
TINarrativeEventTemplate.event_PostApoc_FactionPonderSubmit.query=世界在烈火与硫磺的暴雨中终结时，我们之中的大多数人只能祈祷。当天空被灰烬遮蔽，大地冻结成一片苍白，我们只能幻想，光明终将再次照耀黑暗的世界，以此来填补腹中那啃噬心灵的空虚。<br/><br/>终于，漫长的寒冬结束，我们缓缓走出庇护所，开始重建文明。在过去的一个世纪里，我们修复了城市，重新安置了家庭；然而尽管如此，这个世界在许多方面依然破碎而残缺，因为，核弹落地之日，就是我们自身的一部分永远焚毁之时。唯有我们那份持久的信念，固执地相信更美好的明天正在等待我们，才能支撑我们继续前行。<br/><br/>如今，我们的信念终于得到了回应。宇宙中并非只有我们。我们不再需要独自承受苦难，向一个漠不关心的世界哭泣求索；因为使徒已经看见了我们，而且用自己的光芒为我们指引前路。<br/><br/>我们是信仰的守护者，有责任伸出双手，握住使徒伸来的手，热情地欢迎它们与我们同行。
TINarrativeEventTemplate.event_PostApoc_FactionPonderSubmit.option0=唯有爱它们，我们才能重新学会爱自己。
TINarrativeEventTemplate.event_PostApoc_FactionPonderSubmit.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_FactionPonderSubmit.optionResult0=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_FactionPonderAppease=在《疮痍大地》中绥靖安抚
TINarrativeEventTemplate.event_PostApoc_FactionPonderAppease.summary=我们的世界刚刚走出寒冬战争的阴影，外星人就降临了，这一切意味着什么？
TINarrativeEventTemplate.event_PostApoc_FactionPonderAppease.query=在历史书中，我们总会问自己：是谁该为寒冬战争负责？关于这个问题，人们已经倾注了太多笔墨，而这个问题又与我们的文明基石息息相关。博弈论、边缘政策、即时报复、相互确保毁灭——这些精巧而冷酷的术语，都是用来描述一场预先设想的全球大规模杀戮。当然，这从来不是<i>我们</i>的本意，<i>我们</i>从未想过要屠戮数以百万计的无辜者；我们只是想阻止<i>对方</i>这么做。一切都是<i>他们</i>的错，是<i>他们</i>逼迫我们采取行动。<br/><br/>但事实上，一切都出自我们自己之手：是我们所有人，整个人类种族。早在寒冬战争爆发之前的几个世纪里，我们不断把破坏的循环推向新的高度，戴着丝绒手套，挥舞着白旗，试图掩盖沾满鲜血的手。尽管我们总说，自己是一个开明的种族，但我们真正的本性却一次又一次地暴露无遗。我们已毫无疑问地证明了，人类这个物种并不适合自我治理。<br/><br/>那么，外星文明会如何看待这一切呢？它们能否看到人类超越了自身的缺陷，终于吸取了教训，决心加入更广阔的银河，成为负责任的善良公民？还是会认为，我们只不过是疯狗，为了他人的安全，一定要囚禁甚至扑杀我们？
TINarrativeEventTemplate.event_PostApoc_FactionPonderAppease.option0=为了我们大家的福祉，但愿它们的看法是前者。
TINarrativeEventTemplate.event_PostApoc_FactionPonderAppease.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_FactionPonderAppease.optionResult0=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_FactionPonderCooperate=在《疮痍大地》中合作共赢
TINarrativeEventTemplate.event_PostApoc_FactionPonderCooperate.summary=我们的世界刚刚走出寒冬战争的阴影，外星人就降临了，这一切意味着什么？
TINarrativeEventTemplate.event_PostApoc_FactionPonderCooperate.query=原子弹的发明无疑是人类科学家最伟大的成就。在人类的历史中，这是我们首次成功驾驭了宇宙的基本相互作用之一，而且正是这种力量驱动着恒星本身。这一成就证明，如果科学可以跨越国界，自由发展，那会取得怎样的辉煌成果。<br/><br/>但是，原子弹也成为了我们最大的失败。我们渴望揭开宇宙的奥秘，却在这个过程中忽视了一个问题：一旦人类掌握了这些秘密，我们的同类会如何使用它们？正如量子力学所说，我们仅仅是观察世界，就已经参与其中，而且改变了世界。我们未能意识到科学家肩负的巨大责任，之后就让整个世界为此付出了代价。<br/><br/>然而，科学的意义就在于从失败中学习教训。寒冬战争的爆发，是因为我们未能理解自己的同胞，让恐惧未知战胜了人性中的善良。如今，面对来自星辰的外星文明，我们有机会做得更好。我们有责任以庄重而真诚的态度去接触这些新来者，以平等的参与者身份与他们交流互动。
TINarrativeEventTemplate.event_PostApoc_FactionPonderCooperate.option0=我们绝不能浪费人类的第二次机会。
TINarrativeEventTemplate.event_PostApoc_FactionPonderCooperate.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_FactionPonderCooperate.optionResult0=<skip/>

TINarrativeEventTemplate.displayName.event_PostApoc_FactionPonderEscape=在《疮痍大地》中逃离一切
TINarrativeEventTemplate.event_PostApoc_FactionPonderEscape.summary=我们的世界刚刚走出寒冬战争的阴影，外星人就降临了，这一切意味着什么？
TINarrativeEventTemplate.event_PostApoc_FactionPonderEscape.query=人类一直梦想着飞翔。从代达罗斯与伊卡洛斯的寓言故事，到莱特兄弟的飞行壮举，我们始终渴望挣脱大地的束缚。<br/><br/>第一颗人造卫星发射升空时，我们甚至开始怀揣更大的梦想。随后的短短数年，堪称真正的黄金时代：最杰出的地球智库竞相突破地球引力的牢笼，迈出勇敢的第一步，走向充满无限可能的银河。<br/><br/>然而，这一切终究未能实现。寒冬战争宣告了新的黑暗时代来临，扑灭了我们对美好未来的所有光明希冀。更加讽刺的是，我们如今更有理由逃离这颗遭到辐射污染的冰冷星球，却几乎无力采取任何行动。<br/><br/>但如今，一切再次改变。来自遥远星辰的外星人降临，无可辩驳地证明了太空生存与星际旅行的可能性。一道划破天际的闪光，瞬间让数百年前所有梦想者的信念都得到了印证。外星人让我们明白，我们曾经敢于相信的那个未来，依然真实存在。
TINarrativeEventTemplate.event_PostApoc_FactionPonderEscape.option0=我们只需要伸出手抓住未来就好。
TINarrativeEventTemplate.event_PostApoc_FactionPonderEscape.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_FactionPonderEscape.optionResult0=<skip/>


// TRANSLATION BATCH 2
TINarrativeEventTemplate.displayName.event_PostApoc_Anti-WarlordCampaign=抵抗军阀战役
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.summary={targetNationNameWithArticleCap}已发起一场战役，旨在从军阀手中夺回领土。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.query=战争结束后，{targetNationNameWithArticle}政府无法控制自己的全部领土。交通和通信线路中断，大量安全部队被歼灭或逃离，面对突如其来的流亡危机，关键官员要么束手无策，要么在混乱中失踪。在权力真空的状态下，涌现出一批军阀及其追随者，他们以提供安全为条件，要求人们向其效忠。<br/><br/>如今，{targetNationAdjective}政府已重新组建，{targetNationNameWithArticle}只能存在一个合法政府。官员们承诺将在年底之前严打违法行为，恢复边境秩序。但问题是，如何做到？
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option0=正面直接进攻。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option0.outcome0=成功。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option0.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option0.outcome0.Detail=突袭行动一切顺利！军阀已被迫就范，{targetNationNameWithArticle}正在逐步恢复秩序。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option0.outcome1=失败。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option0.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option0.outcome1.Detail=此次袭击乱成了一锅粥，导致大量人员伤亡。许多敌方战斗人员逃脱，继续通过游击战的形式破坏{targetNationNameWithArticle}的安全。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option1=以新政府的身份承诺给予特赦和合法性。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option1.outcome0=成功。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option1.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option1.outcome0.Detail=军阀总喜欢给自己找个冠冕堂皇的借口，比如：只是在动荡时期为了维持秩序而“不得不采取行动”。我们告诉他们，他们已经履行了对{targetNationNameWithArticle}的职责，成功迎合了他们的自尊心。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option1.outcome1=失败。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option1.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option1.outcome1.Detail=军阀拒绝承认{targetNationAdjective}政府的合法性。{targetNationAdjective}政府别无选择，只能下令发动正面强攻，导致大量人员伤亡，还有敌方战斗人员逃脱。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option2=收买他们的手下，瓦解其势力。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option2.outcome0=成功。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option2.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option2.outcome0.Detail=我们对军阀的手下们保证，每天提供三顿饭菜和热水澡，于是他们毫不犹豫，纷纷倒戈。由于无人愿意执行军阀的命令，军阀失去了话语权，被迫投降。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option2.outcome1=失败。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option2.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option2.outcome1.Detail=不幸的是，军阀心存妄想，自认为是在为更高尚的事业而战，连他们的部下也深信不疑。{targetNationAdjective}政府别无选择，只能下令发动正面强攻，导致大量人员伤亡，还有敌方战斗人员逃脱。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option3=派遣特工刺杀他们的领袖。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.optionDetail3=<skip/>
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option3.outcome0=成功。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option3.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option3.outcome0.Detail=行动成功了！下属们发现，军阀死在了自己的床上。没有人相信这是自然死亡，但既然没有活着的领袖可以依靠，也就没人愿意继续留下。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option3.outcome1=失败。
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option3.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_Anti-WarlordCampaign.option3.outcome1.Detail=行动失败了。我们的特工被吊起来示众，以示警告。{targetNationAdjective}政府别无选择，只能下令发动正面强攻，导致大量人员伤亡，还有敌方战斗人员逃脱。


// TRANSLATION BATCH 2
TINarrativeEventTemplate.displayName.event_PostApoc_NuclearFacilitiesAttacked=核设施遭到袭击
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.summary=意外事件，一伙武装分子占领了{targetNationNameWithArticle}一处存放核武器的设施。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.query=幸运的是，{targetNationNameWithArticle}的核指挥与控制系统经过精心设计，可以防止任何未经授权的发射或引爆——这是从寒冬战争中汲取的深刻教训。然而，有些官员如今已被追究，需要为这起闯入事件负责；还有一些军事领袖需要应对{targetNationNameWithArticle}核威慑力受损的状况，对他们而言，这种防控保障只能带来一丝冰冷的安慰。<br/><br/>截至目前，这些激进分子只发出了信息，要求{targetNationNameWithArticle}自愿废止自己的核计划，否则就会面临本国和平派民众的愤怒。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option0=某人的脑袋保不住了。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.optionDetail0=<skip/>
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.optionResult0={summary}
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option1=紧急派遣快速反应部队赶赴现场。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.optionDetail1=<skip/>
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option1.outcome0=成功。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option1.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option1.outcome0.Detail=在夜色掩护下，一支特种部队乘坐直升机突袭了这座设施。他们成功攻占了控制中心和导弹发射井，消灭了武装分子，阻止他们造成重大破坏。幸存下来的人将会按照叛国罪起诉并定罪。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option1.outcome1=失败。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option1.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option1.outcome1.Detail=在夜色掩护下，一支特种部队乘坐直升机突袭了这座设施。遗憾的是，他们未能阻止核弹头及其他支持设施遭到摧毁。剩余的武装分子随即投降，并且宣称自己的任务已经完成。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option2=包围现场，派出地面部队夺回设施。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.optionDetail2=<skip/>
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option2.outcome0=成功。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option2.outcome0.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option2.outcome0.Detail=一支地面部队迅速集结，对这座设施展开炮击，然后发起进攻。他们成功攻占了控制中心和导弹发射井，消灭了武装分子，阻止他们造成重大破坏。幸存下来的人将会按照叛国罪起诉并定罪。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option2.outcome1=失败。
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option2.outcome1.Summary={summary}
TINarrativeEventTemplate.event_PostApoc_NuclearFacilitiesAttacked.option2.outcome1.Detail=一支地面部队迅速集结，对这座设施展开炮击，然后发起进攻。遗憾的是，他们未能阻止核弹头及其他支持设施遭到摧毁。剩余的武装分子随即投降，并且宣称自己的任务已经完成。
