import { GameVersionCode } from './version';

interface LocalizedUi {
    adjacencies: string;
    baseAvailabilityChance: string;
    claims: string;
    completableOnceGlobally: string;
    completionQuote: string;
    completionText: string;
    cost: string;
    effects: string;
    endgameTech: string;
    factionAlways: string;
    factionPrereq: string;
    fullTextSearch: string;
    hiddenEffect: string;
    initialUnlockChance: string;
    markDone: string;
    markUndone: string;
    clearAllProgress: string;
    clearAllProgressTooltip: string;
    maximumUnlockChance: string;
    milestoneNeeded: string;
    modulesUnlocked: string;
    monthlyUnlockChanceIncrease: string;
    orgGranted: string;
    orgsAddedToMarket: string;
    repeatable: string;
    requiredResearch: string;
    resourcesGranted: string;
    search: string;
    seeEntireTree: string;
    seeTreeForThisNode: string;
    showProjects: string;
    summary: string;
    totalTreeCost: string;
    traits: string;
    unblocksOneOrMoreModules: string;
    unblocksResearch: string;
}

const englishUi: LocalizedUi = {
    adjacencies: "Adjacencies",
    baseAvailabilityChance: "Base Availability Chance",
    claims: "Claims",
    completableOnceGlobally: "Completable once globally",
    completionQuote: "Completion Quote",
    completionText: "Completion Text",
    cost: "Cost",
    effects: "Effects",
    endgameTech: "Endgame tech",
    factionAlways: "Always available to",
    factionPrereq: "Only Available to",
    fullTextSearch: "Full Text Search",
    hiddenEffect: "Hidden effect: ",
    initialUnlockChance: "Initial Unlock Chance",
    markDone: "Mark done",
    markUndone: "Mark undone",
    clearAllProgress: "Clear All Progress",
    clearAllProgressTooltip: "Clears all research progress and reloads the page",
    maximumUnlockChance: "Maximum Unlock Chance",
    milestoneNeeded: "Milestone Needed",
    modulesUnlocked: "Modules Unlocked",
    monthlyUnlockChanceIncrease: "Monthly Unlock Chance Increase",
    orgGranted: "Org Granted",
    orgsAddedToMarket: "Orgs Added to Market",
    repeatable: "Repeatable",
    requiredResearch: "Required Research",
    resourcesGranted: "Resources Granted",
    search: "Search",
    seeEntireTree: "See entire tree",
    seeTreeForThisNode: "See tree for this node",
    showProjects: "Show Projects",
    summary: "Summary",
    totalTreeCost: "Total Tree Cost",
    traits: "Councilor Traits Available",
    unblocksOneOrMoreModules: "Unlocks one or more modules.",
    unblocksResearch: "Unblocks Research",
};

export type Language = {
    code: string;
    icon: string;
    name: string;
    uiTexts: LocalizedUi;
    locale: string;
    availableVersions: GameVersionCode[];
}

const chsUi: LocalizedUi = {
    adjacencies: "邻接关系",
    baseAvailabilityChance: "基础可用几率",
    claims: "声明",
    completableOnceGlobally: "全球只能完成一次",
    completionQuote: "完成引述",
    completionText: "完成文本",
    cost: "成本",
    effects: "效果",
    endgameTech: "终局科技",
    factionAlways: "始终可用于",
    factionPrereq: "仅限于",
    fullTextSearch: "全文搜索",
    hiddenEffect: "隐藏效果：",
    initialUnlockChance: "初始解锁几率",
    markDone: "标记为完成",
        markUndone: "标记为未完成",
    clearAllProgress: "清除所有进度",
    clearAllProgressTooltip: "清除所有研究进度并重新加载页面",
    maximumUnlockChance: "最大解锁几率",
    milestoneNeeded: "需要里程碑",
    modulesUnlocked: "解锁模块",
    monthlyUnlockChanceIncrease: "每月解锁几率增加",
    orgGranted: "获得组织",
    orgsAddedToMarket: "市场新增组织",
    repeatable: "可重复",
    requiredResearch: "需要研究",
    resourcesGranted: "获得资源",
    search: "搜索",
    seeEntireTree: "查看完整技术树",
    seeTreeForThisNode: "查看该节点的技术树",
    showProjects: "显示项目",
    summary: "摘要",
    totalTreeCost: "总树形成本",
    traits: "可用理事特质",
    unblocksOneOrMoreModules: "解锁一个或多个模块。",
    unblocksResearch: "解锁研究",
};

const chtUi: LocalizedUi = {
    adjacencies: "鄰接關係",
    baseAvailabilityChance: "基礎可用機率",
    claims: "聲明",
    completableOnceGlobally: "全球只能完成一次",
    completionQuote: "完成引述",
    completionText: "完成文本",
    cost: "成本",
    effects: "效果",
    endgameTech: "終局科技",
    factionAlways: "始終可用於",
    factionPrereq: "僅限於",
    fullTextSearch: "全文搜索",
    hiddenEffect: "隱藏效果：",
    initialUnlockChance: "初始解鎖機率",
    markDone: "標記為完成",
    markUndone: "標記為未完成",
    clearAllProgress: "清除所有進度",
    clearAllProgressTooltip: "清除所有研究進度並重新載入頁面",
    maximumUnlockChance: "最大解鎖機率",
    milestoneNeeded: "需要里程碑",
    modulesUnlocked: "解鎖模組",
    monthlyUnlockChanceIncrease: "每月解鎖機率增加",
    orgGranted: "獲得組織",
    orgsAddedToMarket: "市場新增組織",
    repeatable: "可重複",
    requiredResearch: "需要研究",
    resourcesGranted: "獲得資源",
    search: "搜索",
    seeEntireTree: "查看完整技術樹",
    seeTreeForThisNode: "查看該節點的技術樹",
    showProjects: "顯示項目",
    summary: "摘要",
    totalTreeCost: "總樹形成本",
    traits: "可用理事特質",
    unblocksOneOrMoreModules: "解鎖一個或多個模組。",
    unblocksResearch: "解鎖研究",
};

const deuUi: LocalizedUi = {
    adjacencies: "Angrenzende",
    baseAvailabilityChance: "Grundchance der Verfügbarkeit",
    claims: "Ansprüche",
    completableOnceGlobally: "Weltweit nur einmal abschließbar",
    completionQuote: "Abschlusszitat",
    completionText: "Abschlusstext",
    cost: "Kosten",
    effects: "Effekte",
    endgameTech: "Endspiel-Technologie",
    factionAlways: "Immer verfügbar für",
    factionPrereq: "Nur verfügbar für",
    fullTextSearch: "Volltextsuche",
    hiddenEffect: "Versteckter Effekt: ",
    initialUnlockChance: "Anfängliche Freischaltchance",
    markDone: "Als erledigt markieren",
    markUndone: "Als unerledigt markieren",
    clearAllProgress: "Alle Fortschritte löschen",
    clearAllProgressTooltip: "Löscht alle Forschungsfortschritte und lädt die Seite neu",
    maximumUnlockChance: "Maximale Freischaltchance",
    milestoneNeeded: "Benötigter Meilenstein",
    modulesUnlocked: "Freigeschaltete Module",
    monthlyUnlockChanceIncrease: "Monatliche Erhöhung der Freischaltchance",
    orgGranted: "Gewährte Organisation",
    orgsAddedToMarket: "Zum Markt hinzugefügte Organisationen",
    repeatable: "Wiederholbar",
    requiredResearch: "Erforderliche Forschung",
    resourcesGranted: "Gewährte Ressourcen",
    search: "Suche",
    seeEntireTree: "Gesamten Baum anzeigen",
    seeTreeForThisNode: "Baum für diesen Knoten anzeigen",
    showProjects: "Projekte anzeigen",
    summary: "Zusammenfassung",
    totalTreeCost: "Gesamte Baumkosten",
    traits: "Verfügbare Ratseigenschaften",
    unblocksOneOrMoreModules: "Schaltet ein oder mehrere Module frei.",
    unblocksResearch: "Schaltet Forschung frei",
};

const espUi: LocalizedUi = {
    adjacencies: "Adyacencias",
    baseAvailabilityChance: "Probabilidad Base de Disponibilidad",
    claims: "Afirmaciones",
    completableOnceGlobally: "Completable una vez globalmente",
    completionQuote: "Cita de Finalización",
    completionText: "Texto de Finalización",
    cost: "Costo",
    effects: "Efectos",
    endgameTech: "Tecnología de fin de juego",
    factionAlways: "Siempre disponible para",
    factionPrereq: "Solo disponible para",
    fullTextSearch: "Búsqueda de texto completo",
    hiddenEffect: "Efecto oculto: ",
    initialUnlockChance: "Probabilidad Inicial de Desbloqueo",
    markDone: "Marcar como hecho",
    markUndone: "Desmarcar",
    clearAllProgress: "Borrar Todo Progreso",
    clearAllProgressTooltip: "Borra todo el progreso de investigación y recarga la página",
    maximumUnlockChance: "Probabilidad Máxima de Desbloqueo",
    milestoneNeeded: "Hito Necesario",
    modulesUnlocked: "Módulos Desbloqueados",
    monthlyUnlockChanceIncrease: "Aumento Mensual de Probabilidad de Desbloqueo",
    orgGranted: "Organización Otorgada",
    orgsAddedToMarket: "Organizaciones Añadidas al Mercado",
    repeatable: "Repetible",
    requiredResearch: "Investigación Requerida",
    resourcesGranted: "Recursos Otorgados",
    search: "Buscar",
    seeEntireTree: "Ver árbol completo",
    seeTreeForThisNode: "Ver árbol para este nodo",
    showProjects: "Mostrar Proyectos",
    summary: "Resumen",
    totalTreeCost: "Costo Total del Árbol",
    traits: "Rasgos de Consejero Disponibles",
    unblocksOneOrMoreModules: "Desbloquea uno o más módulos.",
    unblocksResearch: "Desbloquea Investigación",
};

const frUi: LocalizedUi = {
    adjacencies: "Adjacences",
    baseAvailabilityChance: "Chance de disponibilité de base",
    claims: "Revendications",
    completableOnceGlobally: "Complétable une fois globalement",
    completionQuote: "Citation de fin",
    completionText: "Texte de fin",
    cost: "Coût",
    effects: "Effets",
    endgameTech: "Technologie de fin de partie",
    factionAlways: "Toujours disponible pour",
    factionPrereq: "Uniquement disponible pour",
    fullTextSearch: "Recherche en texte intégral",
    hiddenEffect: "Effet caché : ",
    initialUnlockChance: "Chance de déverrouillage initiale",
    markDone: "Marquer comme fait",
    markUndone: "Marquer comme non fait",
    clearAllProgress: "Effacer Tous Progrès",
    clearAllProgressTooltip: "Efface tous les progrès de recherche et recharge la page",
    maximumUnlockChance: "Chance de déverrouillage maximale",
    milestoneNeeded: "Jalon nécessaire",
    modulesUnlocked: "Modules déverrouillés",
    monthlyUnlockChanceIncrease: "Augmentation mensuelle de la chance de déverrouillage",
    orgGranted: "Organisation accordée",
    orgsAddedToMarket: "Organisations ajoutées au marché",
    repeatable: "Répétable",
    requiredResearch: "Recherche requise",
    resourcesGranted: "Ressources accordées",
    search: "Rechercher",
    seeEntireTree: "Voir l'arbre entier",
    seeTreeForThisNode: "Voir l'arbre pour ce nœud",
    showProjects: "Afficher les projets",
    summary: "Résumé",
    totalTreeCost: "Coût total de l'arbre",
    traits: "Traits de conseiller disponibles",
    unblocksOneOrMoreModules: "Débloque un ou plusieurs modules.",
    unblocksResearch: "Débloque la recherche",
};

const jpnUi: LocalizedUi = {
    adjacencies: "隣接関係",
    baseAvailabilityChance: "基本利用可能性",
    claims: "主張",
    completableOnceGlobally: "全体で一度だけ完了可能",
    completionQuote: "完了時の引用",
    completionText: "完了テキスト",
    cost: "コスト",
    effects: "効果",
    endgameTech: "エンドゲーム技術",
    factionAlways: "常に利用可能",
    factionPrereq: "限定利用可能",
    fullTextSearch: "全文検索",
    hiddenEffect: "隠し効果：",
    initialUnlockChance: "初期解除確率",
    markDone: "完了としてマーク",
    markUndone: "未完了としてマーク",
    clearAllProgress: "全進歩をクリア",
    clearAllProgressTooltip: "すべての研究進歩をクリアしてページを再読み込みします",
    maximumUnlockChance: "最大解除確率",
    milestoneNeeded: "必要なマイルストーン",
    modulesUnlocked: "解除されたモジュール",
    monthlyUnlockChanceIncrease: "月間解除確率増加",
    orgGranted: "付与される組織",
    orgsAddedToMarket: "市場に追加される組織",
    repeatable: "繰り返し可能",
    requiredResearch: "必要な研究",
    resourcesGranted: "付与される資源",
    search: "検索",
    seeEntireTree: "ツリー全体を表示",
    seeTreeForThisNode: "このノードのツリーを表示",
    showProjects: "プロジェクトを表示",
    summary: "概要",
    totalTreeCost: "ツリー総コスト",
    traits: "利用可能な評議員特性",
    unblocksOneOrMoreModules: "1つ以上のモジュールをアンロックします。",
    unblocksResearch: "研究をアンロック",
};

const polUi: LocalizedUi = {
    adjacencies: "Sąsiedztwa",
    baseAvailabilityChance: "Podstawowa szansa dostępności",
    claims: "Roszczenia",
    completableOnceGlobally: "Ukończalne tylko raz globalnie",
    completionQuote: "Cytat przy ukończeniu",
    completionText: "Tekst ukończenia",
    cost: "Koszt",
    effects: "Efekty",
    endgameTech: "Technologia końca gry",
    factionAlways: "Zawsze dostępne dla",
    factionPrereq: "Dostępne tylko dla",
    fullTextSearch: "Wyszukiwanie pełnotekstowe",
    hiddenEffect: "Ukryty efekt: ",
    initialUnlockChance: "Początkowa szansa odblokowania",
    markDone: "Oznacz jako ukończone",
    markUndone: "Oznacz jako nieukończone",
    clearAllProgress: "Wyczyść Cały Postęp",
    clearAllProgressTooltip: "Czyści cały postęp badań i przeładowuje stronę",
    maximumUnlockChance: "Maksymalna szansa odblokowania",
    milestoneNeeded: "Wymagany kamień milowy",
    modulesUnlocked: "Odblokowane moduły",
    monthlyUnlockChanceIncrease: "Miesięczny wzrost szansy odblokowania",
    orgGranted: "Przyznana organizacja",
    orgsAddedToMarket: "Organizacje dodane do rynku",
    repeatable: "Powtarzalne",
    requiredResearch: "Wymagane badania",
    resourcesGranted: "Przyznane zasoby",
    search: "Szukaj",
    seeEntireTree: "Zobacz całe drzewo",
    seeTreeForThisNode: "Zobacz drzewo dla tego węzła",
    showProjects: "Pokaż projekty",
    summary: "Podsumowanie",
    totalTreeCost: "Całkowity koszt drzewa",
    traits: "Dostępne cechy radnych",
    unblocksOneOrMoreModules: "Odblokowuje jeden lub więcej modułów.",
    unblocksResearch: "Odblokowuje badania",
};

const porUi: LocalizedUi = {
    adjacencies: "Adjacências",
    baseAvailabilityChance: "Chance Base de Disponibilidade",
    claims: "Reivindicações",
    completableOnceGlobally: "Completável uma vez globalmente",
    completionQuote: "Citação de Conclusão",
    completionText: "Texto de Conclusão",
    cost: "Custo",
    effects: "Efeitos",
    endgameTech: "Tecnologia de fim de jogo",
    factionAlways: "Sempre disponível para",
    factionPrereq: "Disponível apenas para",
    fullTextSearch: "Pesquisa de texto completo",
    hiddenEffect: "Efeito oculto: ",
    initialUnlockChance: "Chance Inicial de Desbloqueio",
    markDone: "Marcar como concluído",
    markUndone: "Marcar como não concluído",
    clearAllProgress: "Limpar Todo Progresso",
    clearAllProgressTooltip: "Limpa todo o progresso de pesquisa e recarrega a página",
    maximumUnlockChance: "Chance Máxima de Desbloqueio",
    milestoneNeeded: "Marco Necessário",
    modulesUnlocked: "Módulos Desbloqueados",
    monthlyUnlockChanceIncrease: "Aumento Mensal da Chance de Desbloqueio",
    orgGranted: "Organização Concedida",
    orgsAddedToMarket: "Organizações Adicionadas ao Mercado",
    repeatable: "Repetível",
    requiredResearch: "Pesquisa Necessária",
    resourcesGranted: "Recursos Concedidos",
    search: "Pesquisar",
    seeEntireTree: "Ver árvore completa",
    seeTreeForThisNode: "Ver árvore para este nó",
    showProjects: "Mostrar Projetos",
    summary: "Resumo",
    totalTreeCost: "Custo Total da Árvore",
    traits: "Características de Conselheiro Disponíveis",
    unblocksOneOrMoreModules: "Desbloqueia um ou mais módulos.",
    unblocksResearch: "Desbloqueia Pesquisa",
};

const korUi: LocalizedUi = {
    adjacencies: "인접 관계",
    baseAvailabilityChance: "기본 가용 확률",
    claims: "영유권",
    completableOnceGlobally: "전 세계에서 한 번만 완료 가능",
    completionQuote: "완료 인용구",
    completionText: "완료 텍스트",
    cost: "비용",
    effects: "효과",
    endgameTech: "엔드게임 기술",
    factionAlways: "항상 사용 가능한 세력",
    factionPrereq: "사용 가능한 세력 제한",
    fullTextSearch: "전체 텍스트 검색",
    hiddenEffect: "숨겨진 효과: ",
    initialUnlockChance: "초기 해제 확률",
    markDone: "완료 표시",
    markUndone: "완료 취소",
    clearAllProgress: "모든 진행도 초기화",
    clearAllProgressTooltip: "모든 연구 진행도를 초기화하고 페이지를 새로 고칩니다",
    maximumUnlockChance: "최대 해제 확률",
    milestoneNeeded: "필요한 이정표",
    modulesUnlocked: "해제된 모듈",
    monthlyUnlockChanceIncrease: "월간 해제 확률 증가",
    orgGranted: "획득한 조직",
    orgsAddedToMarket: "시장에 추가된 조직",
    repeatable: "반복 가능",
    requiredResearch: "필요 연구",
    resourcesGranted: "획득 자원",
    search: "검색",
    seeEntireTree: "전체 트리 보기",
    seeTreeForThisNode: "이 노드의 트리 보기",
    showProjects: "프로젝트 표시",
    summary: "요약",
    totalTreeCost: "트리 총 비용",
    traits: "사용 가능한 고문 특성",
    unblocksOneOrMoreModules: "하나 이상의 모듈을 해제합니다.",
    unblocksResearch: "연구를 해제",
};

const rusUi: LocalizedUi = {
    adjacencies: "Смежности",
    baseAvailabilityChance: "Базовый шанс доступности",
    claims: "Претензии",
    completableOnceGlobally: "Завершается только один раз во всём мире",
    completionQuote: "Цитата при завершении",
    completionText: "Текст завершения",
    cost: "Стоимость",
    effects: "Эффекты",
    endgameTech: "Финальная технология",
    factionAlways: "Всегда доступно для",
    factionPrereq: "Доступно только для",
    fullTextSearch: "Полнотекстовый поиск",
    hiddenEffect: "Скрытый эффект: ",
    initialUnlockChance: "Начальный шанс разблокировки",
    markDone: "Отметить выполненным",
    markUndone: "Отметить невыполненным",
    clearAllProgress: "Сбросить весь прогресс",
    clearAllProgressTooltip: "Сбрасывает весь прогресс исследований и перезагружает страницу",
    maximumUnlockChance: "Максимальный шанс разблокировки",
    milestoneNeeded: "Требуемый рубеж",
    modulesUnlocked: "Разблокированные модули",
    monthlyUnlockChanceIncrease: "Ежемесячный прирост шанса разблокировки",
    orgGranted: "Полученная организация",
    orgsAddedToMarket: "Организации, добавленные на рынок",
    repeatable: "Повторяемое",
    requiredResearch: "Необходимое исследование",
    resourcesGranted: "Выданные ресурсы",
    search: "Поиск",
    seeEntireTree: "Показать всё дерево",
    seeTreeForThisNode: "Показать дерево для этого узла",
    showProjects: "Показать проекты",
    summary: "Сводка",
    totalTreeCost: "Общая стоимость дерева",
    traits: "Доступные черты советников",
    unblocksOneOrMoreModules: "Разблокирует один или несколько модулей.",
    unblocksResearch: "Разблокирует исследования",
};

const ukrUi: LocalizedUi = {
    adjacencies: "Суміжності",
    baseAvailabilityChance: "Базовий шанс доступності",
    claims: "Претензії",
    completableOnceGlobally: "Можна завершити лише один раз у світі",
    completionQuote: "Цитата завершення",
    completionText: "Текст завершення",
    cost: "Вартість",
    effects: "Ефекти",
    endgameTech: "Фінальна технологія",
    factionAlways: "Завжди доступно для",
    factionPrereq: "Доступно лише для",
    fullTextSearch: "Повнотекстовий пошук",
    hiddenEffect: "Прихований ефект: ",
    initialUnlockChance: "Початковий шанс розблокування",
    markDone: "Позначити завершеним",
    markUndone: "Позначити незавершеним",
    clearAllProgress: "Очистити весь прогрес",
    clearAllProgressTooltip: "Очищає весь прогрес досліджень і перезавантажує сторінку",
    maximumUnlockChance: "Максимальний шанс розблокування",
    milestoneNeeded: "Потрібний рубіж",
    modulesUnlocked: "Розблоковані модулі",
    monthlyUnlockChanceIncrease: "Щомісячне зростання шансу розблокування",
    orgGranted: "Надана організація",
    orgsAddedToMarket: "Організації, додані на ринок",
    repeatable: "Повторюване",
    requiredResearch: "Потрібне дослідження",
    resourcesGranted: "Надані ресурси",
    search: "Пошук",
    seeEntireTree: "Переглянути все дерево",
    seeTreeForThisNode: "Переглянути дерево для цього вузла",
    showProjects: "Показати проєкти",
    summary: "Підсумок",
    totalTreeCost: "Загальна вартість дерева",
    traits: "Доступні риси радників",
    unblocksOneOrMoreModules: "Розблоковує один або більше модулів.",
    unblocksResearch: "Розблоковує дослідження",
};

const stableAndExperimental: GameVersionCode[] = ['stable', 'experimental'];
const experimentalOnly: GameVersionCode[] = ['experimental'];

export const Languages: Record<string, Language> = {
    en: { code: 'en', icon: '🇬🇧', name: 'English', uiTexts: englishUi, locale: 'en', availableVersions: stableAndExperimental },
    chs: { code: 'chs', icon: '🇨🇳', name: '简体中文', uiTexts: chsUi, locale: 'zh', availableVersions: stableAndExperimental },
    cht: { code: 'cht', icon: '🇨🇳', name: '繁體中文', uiTexts: chtUi, locale: 'zh', availableVersions: stableAndExperimental },
    deu: { code: 'deu', icon: '🇩🇪', name: 'Deutsch', uiTexts: deuUi, locale: 'de', availableVersions: stableAndExperimental },
    esp: { code: 'esp', icon: '🇪🇸', name: 'Español', uiTexts: espUi, locale: 'es', availableVersions: stableAndExperimental },
    fr: { code: 'fr', icon: '🇫🇷', name: 'Français', uiTexts: frUi, locale: 'fr', availableVersions: stableAndExperimental },
    jpn: { code: 'jpn', icon: '🇯🇵', name: '日本語', uiTexts: jpnUi, locale: 'ja', availableVersions: stableAndExperimental },
    pol: { code: 'pol', icon: '🇵🇱', name: 'Polski', uiTexts: polUi, locale: 'pl', availableVersions: stableAndExperimental },
    por: { code: 'por', icon: '🇧🇷', name: 'Português', uiTexts: porUi, locale: 'pt', availableVersions: stableAndExperimental },
    kor: { code: 'kor', icon: '🇰🇷', name: '한국어', uiTexts: korUi, locale: 'ko', availableVersions: experimentalOnly },
    rus: { code: 'rus', icon: '🇷🇺', name: 'Русский', uiTexts: rusUi, locale: 'ru', availableVersions: experimentalOnly },
    ukr: { code: 'ukr', icon: '🇺🇦', name: 'Українська', uiTexts: ukrUi, locale: 'uk', availableVersions: experimentalOnly },
};

export const DefaultLanguage = Languages.en;
