import { GameVersionCode } from './version';

export interface LocalizedUi {
    adjacencies: string;
    baseAvailabilityChance: string;
    claims: string;
    claimsScenario: string;
    completableOnceGlobally: string;
    completionQuote: string;
    completionText: string;
    cost: string;
    effects: string;
    endgameTech: string;
    factionAlways: string;
    factionPrereq: string;
    fullTextSearch: string;
    hiddenEffect: string;
    initialUnlockChance: string;
    markDone: string;
    markUndone: string;
    clearAllProgress: string;
    clearAllProgressTooltip: string;
    maximumUnlockChance: string;
    milestoneNeeded: string;
    modulesUnlocked: string;
    monthlyUnlockChanceIncrease: string;
    orgGranted: string;
    orgsAddedToMarket: string;
    repeatable: string;
    requiredResearch: string;
    resourcesGranted: string;
    search: string;
    seeEntireTree: string;
    seeTreeForThisNode: string;
    browseGamefiles: string;
    projectSourceCode: string;
    showProjects: string;
    summary: string;
    totalTreeCost: string;
    traits: string;
    unblocksOneOrMoreModules: string;
    unblocksResearch: string;
    randomFaction: string;
    costBreakdownTooltip: string;
    copyToClipboard: string;
    copiedLabel: string;
    fuelPerTank: string;
    weightedBuildMaterialsLabel: string;
    driveSpecsShared: string;
    driveColumnLabel: string;
    thrustersLabel: string;
    thrustNLabel: string;
    thrustRatingGWLabel: string;
    requiredPowerLabel: string;
    flatMassLabel: string;
    drivesHeading: string;
    driveChartTitle: string;
    driveChartSubtitle: string;
    backToTechTree: string;
    closeLabel: string;
    cruiseThrust: string;
    combatThrust: string;
    showLabels: string;
    loadingDrives: string;
    exhaustVelocityLabel: string;
    unknownDrive: string;
    notAvailable: string;
    orLabel: string;
    andLabel: string;
    factionProjectTitle: string;
    globalResearchTitle: string;
    claimGained: string;
    adjacencyFriendly: string;
    adjacencyGeneral: string;
    scenarioLabel: string;
    settingsMenuLabel: string;
    scenarioSettingsDiscovery: string;
    settingsCurrentScenario: string;
    scenarioStandard: string;
    scenario2003Short: string;
    scenarioBrokenEarthShort: string;
    scenario2003Fallback: string;
    scenarioBrokenEarthFallback: string;
    scenarioTreeStatus: string;
    scenarioViewingStatus: string;
    scenarioLoadingStatus: string;
    scenarioLoadError: string;
    scenarioInitialLoadError: string;
    darkSkiesDlc: string;
    darkSkiesName: string;
    darkSkiesAddition: string;
    scenarioVersion: string;
    technologyGraphAccessible: string;
}

const englishUi: LocalizedUi = {
    adjacencies: "Adjacencies",
    baseAvailabilityChance: "Base Availability Chance",
    claims: "Claims",
    claimsScenario: "{year} start",
    completableOnceGlobally: "Completable once globally",
    completionQuote: "Completion Quote",
    completionText: "Completion Text",
    cost: "Cost",
    effects: "Effects",
    endgameTech: "Endgame tech",
    factionAlways: "Always available to",
    factionPrereq: "Only Available to",
    fullTextSearch: "Full Text Search",
    hiddenEffect: "Hidden effect: ",
    initialUnlockChance: "Initial Unlock Chance",
    markDone: "Mark done",
    markUndone: "Mark undone",
    clearAllProgress: "Clear All Progress",
    clearAllProgressTooltip: "Clears all research progress and reloads the page",
    maximumUnlockChance: "Maximum Unlock Chance",
    milestoneNeeded: "Milestone Needed",
    modulesUnlocked: "Modules Unlocked",
    monthlyUnlockChanceIncrease: "Monthly Unlock Chance Increase",
    orgGranted: "Org Granted",
    orgsAddedToMarket: "Orgs Added to Market",
    repeatable: "Repeatable",
    requiredResearch: "Required Research",
    resourcesGranted: "Resources Granted",
    search: "Search",
    seeEntireTree: "See entire tree",
    seeTreeForThisNode: "See tree for this node",
    browseGamefiles: "Browse gamefiles",
    projectSourceCode: "Project source code",
    showProjects: "Show Projects",
    summary: "Summary",
    totalTreeCost: "Total Tree Cost",
    traits: "Councilor Traits Available",
    unblocksOneOrMoreModules: "Unlocks one or more modules.",
    unblocksResearch: "Unblocks Research",
    randomFaction: "Random",
    costBreakdownTooltip: "Click to see technology cost breakdown",
    copyToClipboard: "Copy to clipboard",
    copiedLabel: "Copied!",
    fuelPerTank: "Fuel per tank",
    weightedBuildMaterialsLabel: "Build materials",
    driveSpecsShared: "Drive specs (shared)",
    driveColumnLabel: "Drive",
    thrustersLabel: "Thrusters",
    thrustNLabel: "Thrust (N)",
    thrustRatingGWLabel: "Thrust Rating (GW)",
    requiredPowerLabel: "Req power",
    flatMassLabel: "Mass (tons)",
    drivesHeading: "Drives",
    driveChartTitle: "Drive chart",
    driveChartSubtitle: "Drag to zoom, double-click to reset. Hover for details; toggle labels to declutter.",
    backToTechTree: "Back to tech tree",
    closeLabel: "Close",
    cruiseThrust: "Cruise thrust",
    combatThrust: "Combat thrust",
    showLabels: "Show labels",
    loadingDrives: "Loading drives…",
    exhaustVelocityLabel: "Exhaust velocity",
    unknownDrive: "Unknown drive",
    notAvailable: "N/A",
    orLabel: "or",
    andLabel: "and",
    factionProjectTitle: "Faction Project",
    globalResearchTitle: "Global Research",
    claimGained: "{nation} gains a claim on {region}",
    adjacencyFriendly: "{region1} and {region2} are now considered to be adjacent for friendly traffic",
    adjacencyGeneral: "{region1} and {region2} are now considered to be adjacent",
    scenarioLabel: "Scenario",
    settingsMenuLabel: "Settings",
    scenarioSettingsDiscovery: "Scenarios available in Settings",
    settingsCurrentScenario: "Settings — current scenario: {scenario}",
    scenarioStandard: "Standard",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Broken Earth",
    scenario2003Fallback: "2003 Scenario",
    scenarioBrokenEarthFallback: "Broken Earth Scenario",
    scenarioTreeStatus: "Scenario: {scenario}",
    scenarioViewingStatus: "Viewing {active} · Loading {target}…",
    scenarioLoadingStatus: "Loading {target}…",
    scenarioLoadError: "Unable to load {scenario}. The previous view remains active.",
    scenarioInitialLoadError: "Unable to load {scenario}. Please try again.",
    darkSkiesDlc: "Dark Skies DLC",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Dark Skies addition",
    scenarioVersion: "{scenario} version",
    technologyGraphAccessible: "Technology graph for {scenario}. A diamond marks nodes added by the Dark Skies DLC.",
};

export type Language = {
    code: string;
    icon: string;
    name: string;
    uiTexts: LocalizedUi;
    locale: string;
    availableVersions: GameVersionCode[];
}

const chsUi: LocalizedUi = {
    adjacencies: "邻接关系",
    baseAvailabilityChance: "基础可用几率",
    claims: "声明",
    claimsScenario: "{year}年开局",
    completableOnceGlobally: "全球只能完成一次",
    completionQuote: "完成引述",
    completionText: "完成文本",
    cost: "成本",
    effects: "效果",
    endgameTech: "终局科技",
    factionAlways: "始终可用于",
    factionPrereq: "仅限于",
    fullTextSearch: "全文搜索",
    hiddenEffect: "隐藏效果：",
    initialUnlockChance: "初始解锁几率",
    markDone: "标记为完成",
        markUndone: "标记为未完成",
    clearAllProgress: "清除所有进度",
    clearAllProgressTooltip: "清除所有研究进度并重新加载页面",
    maximumUnlockChance: "最大解锁几率",
    milestoneNeeded: "需要里程碑",
    modulesUnlocked: "解锁模块",
    monthlyUnlockChanceIncrease: "每月解锁几率增加",
    orgGranted: "获得组织",
    orgsAddedToMarket: "市场新增组织",
    repeatable: "可重复",
    requiredResearch: "需要研究",
    resourcesGranted: "获得资源",
    search: "搜索",
    seeEntireTree: "查看完整技术树",
    seeTreeForThisNode: "查看该节点的技术树",
    browseGamefiles: "浏览游戏文件",
    projectSourceCode: "项目源代码",
    showProjects: "显示项目",
    summary: "摘要",
    totalTreeCost: "总树形成本",
    traits: "可用理事特质",
    unblocksOneOrMoreModules: "解锁一个或多个模块。",
    unblocksResearch: "解锁研究",
    randomFaction: "随机",
    costBreakdownTooltip: "点击查看技术成本明细",
    copyToClipboard: "复制到剪贴板",
    copiedLabel: "已复制！",
    fuelPerTank: "每罐燃料",
    weightedBuildMaterialsLabel: "建造材料",
    driveSpecsShared: "引擎规格（共享）",
    driveColumnLabel: "引擎",
    thrustersLabel: "推进器",
    thrustNLabel: "推力 (N)",
    thrustRatingGWLabel: "推力等级 (GW)",
    requiredPowerLabel: "需求功率",
    flatMassLabel: "质量 (吨)",
    drivesHeading: "引擎",
    driveChartTitle: "引擎图表",
    driveChartSubtitle: "拖动缩放，双击重置。悬停查看详情；切换标签以减少杂乱。",
    backToTechTree: "返回科技树",
    closeLabel: "关闭",
    cruiseThrust: "巡航推力",
    combatThrust: "战斗推力",
    showLabels: "显示标签",
    loadingDrives: "正在加载引擎…",
    exhaustVelocityLabel: "喷射速度",
    unknownDrive: "未知引擎",
    notAvailable: "N/A",
    orLabel: "或",
    andLabel: "和",
    factionProjectTitle: "派系项目",
    globalResearchTitle: "全球研究",
    claimGained: "{nation}获得了对{region}的宣称",
    adjacencyFriendly: "{region1}和{region2}现在被视为友军交通的邻接区域",
    adjacencyGeneral: "{region1}和{region2}现在被视为邻接区域",
    scenarioLabel: "情境",
    settingsMenuLabel: "设置",
    scenarioSettingsDiscovery: "可在设置中选择情境",
    settingsCurrentScenario: "设置 — 当前情境：{scenario}",
    scenarioStandard: "标准",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "疮痍大地",
    scenario2003Fallback: "2003 情境",
    scenarioBrokenEarthFallback: "疮痍大地情境",
    scenarioTreeStatus: "情境：{scenario}",
    scenarioViewingStatus: "正在查看 {active} · 正在加载 {target}…",
    scenarioLoadingStatus: "正在加载 {target}…",
    scenarioLoadError: "无法加载 {scenario}。仍显示先前的科技树。",
    scenarioInitialLoadError: "无法加载 {scenario}。请重试。",
    darkSkiesDlc: "黑暗天空 DLC",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "黑暗天空新增内容",
    scenarioVersion: "{scenario}版本",
    technologyGraphAccessible: "{scenario}的科技图谱。菱形标记由黑暗天空 DLC 新增的节点。",
};

const chtUi: LocalizedUi = {
    adjacencies: "鄰接關係",
    baseAvailabilityChance: "基礎可用機率",
    claims: "聲明",
    claimsScenario: "{year}年開局",
    completableOnceGlobally: "全球只能完成一次",
    completionQuote: "完成引述",
    completionText: "完成文本",
    cost: "成本",
    effects: "效果",
    endgameTech: "終局科技",
    factionAlways: "始終可用於",
    factionPrereq: "僅限於",
    fullTextSearch: "全文搜索",
    hiddenEffect: "隱藏效果：",
    initialUnlockChance: "初始解鎖機率",
    markDone: "標記為完成",
    markUndone: "標記為未完成",
    clearAllProgress: "清除所有進度",
    clearAllProgressTooltip: "清除所有研究進度並重新載入頁面",
    maximumUnlockChance: "最大解鎖機率",
    milestoneNeeded: "需要里程碑",
    modulesUnlocked: "解鎖模組",
    monthlyUnlockChanceIncrease: "每月解鎖機率增加",
    orgGranted: "獲得組織",
    orgsAddedToMarket: "市場新增組織",
    repeatable: "可重複",
    requiredResearch: "需要研究",
    resourcesGranted: "獲得資源",
    search: "搜索",
    seeEntireTree: "查看完整技術樹",
    seeTreeForThisNode: "查看該節點的技術樹",
    browseGamefiles: "瀏覽遊戲檔案",
    projectSourceCode: "項目原始碼",
    showProjects: "顯示項目",
    summary: "摘要",
    totalTreeCost: "總樹形成本",
    traits: "可用理事特質",
    unblocksOneOrMoreModules: "解鎖一個或多個模組。",
    unblocksResearch: "解鎖研究",
    randomFaction: "隨機",
    costBreakdownTooltip: "點擊查看技術成本明細",
    copyToClipboard: "複製到剪貼簿",
    copiedLabel: "已複製！",
    fuelPerTank: "每罐燃料",
    weightedBuildMaterialsLabel: "建造材料",
    driveSpecsShared: "引擎規格（共享）",
    driveColumnLabel: "引擎",
    thrustersLabel: "推進器",
    thrustNLabel: "推力 (N)",
    thrustRatingGWLabel: "推力等級 (GW)",
    requiredPowerLabel: "需求功率",
    flatMassLabel: "質量 (噸)",
    drivesHeading: "引擎",
    driveChartTitle: "引擎圖表",
    driveChartSubtitle: "拖曳縮放，雙擊重置。懸停檢視詳情；切換標籤以減少雜亂。",
    backToTechTree: "返回科技樹",
    closeLabel: "關閉",
    cruiseThrust: "巡航推力",
    combatThrust: "戰鬥推力",
    showLabels: "顯示標籤",
    loadingDrives: "正在載入引擎…",
    exhaustVelocityLabel: "噴射速度",
    unknownDrive: "未知引擎",
    notAvailable: "N/A",
    orLabel: "或",
    andLabel: "和",
    factionProjectTitle: "派系項目",
    globalResearchTitle: "全球研究",
    claimGained: "{nation}獲得了對{region}的宣稱",
    adjacencyFriendly: "{region1}和{region2}現在被視為友軍交通的鄰接區域",
    adjacencyGeneral: "{region1}和{region2}現在被視為鄰接區域",
    scenarioLabel: "情境",
    settingsMenuLabel: "設定",
    scenarioSettingsDiscovery: "可在設定中選擇情境",
    settingsCurrentScenario: "設定 — 目前情境：{scenario}",
    scenarioStandard: "標準",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "瘡痍大地",
    scenario2003Fallback: "2003 情境",
    scenarioBrokenEarthFallback: "瘡痍大地情境",
    scenarioTreeStatus: "情境：{scenario}",
    scenarioViewingStatus: "正在檢視 {active} · 正在載入 {target}…",
    scenarioLoadingStatus: "正在載入 {target}…",
    scenarioLoadError: "無法載入 {scenario}。仍顯示先前的科技樹。",
    scenarioInitialLoadError: "無法載入 {scenario}。請重試。",
    darkSkiesDlc: "黑暗天空 DLC",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "黑暗天空新增內容",
    scenarioVersion: "{scenario}版本",
    technologyGraphAccessible: "{scenario}的科技圖譜。菱形標記由黑暗天空 DLC 新增的節點。",
};

const deuUi: LocalizedUi = {
    adjacencies: "Angrenzende",
    baseAvailabilityChance: "Grundchance der Verfügbarkeit",
    claims: "Ansprüche",
    claimsScenario: "Start {year}",
    completableOnceGlobally: "Weltweit nur einmal abschließbar",
    completionQuote: "Abschlusszitat",
    completionText: "Abschlusstext",
    cost: "Kosten",
    effects: "Effekte",
    endgameTech: "Endspiel-Technologie",
    factionAlways: "Immer verfügbar für",
    factionPrereq: "Nur verfügbar für",
    fullTextSearch: "Volltextsuche",
    hiddenEffect: "Versteckter Effekt: ",
    initialUnlockChance: "Anfängliche Freischaltchance",
    markDone: "Als erledigt markieren",
    markUndone: "Als unerledigt markieren",
    clearAllProgress: "Alle Fortschritte löschen",
    clearAllProgressTooltip: "Löscht alle Forschungsfortschritte und lädt die Seite neu",
    maximumUnlockChance: "Maximale Freischaltchance",
    milestoneNeeded: "Benötigter Meilenstein",
    modulesUnlocked: "Freigeschaltete Module",
    monthlyUnlockChanceIncrease: "Monatliche Erhöhung der Freischaltchance",
    orgGranted: "Gewährte Organisation",
    orgsAddedToMarket: "Zum Markt hinzugefügte Organisationen",
    repeatable: "Wiederholbar",
    requiredResearch: "Erforderliche Forschung",
    resourcesGranted: "Gewährte Ressourcen",
    search: "Suche",
    seeEntireTree: "Gesamten Baum anzeigen",
    seeTreeForThisNode: "Baum für diesen Knoten anzeigen",
    browseGamefiles: "Spieldateien durchsuchen",
    projectSourceCode: "Quellcode des Projekts",
    showProjects: "Projekte anzeigen",
    summary: "Zusammenfassung",
    totalTreeCost: "Gesamte Baumkosten",
    traits: "Verfügbare Ratseigenschaften",
    unblocksOneOrMoreModules: "Schaltet ein oder mehrere Module frei.",
    unblocksResearch: "Schaltet Forschung frei",
    randomFaction: "Zufällig",
    costBreakdownTooltip: "Klicken, um Technologiekostenübersicht anzuzeigen",
    copyToClipboard: "In Zwischenablage kopieren",
    copiedLabel: "Kopiert!",
    fuelPerTank: "Treibstoff pro Tank",
    weightedBuildMaterialsLabel: "Baumaterialien",
    driveSpecsShared: "Antriebsspezifikationen (gemeinsam)",
    driveColumnLabel: "Antrieb",
    thrustersLabel: "Triebwerke",
    thrustNLabel: "Schub (N)",
    thrustRatingGWLabel: "Schubleistung (GW)",
    requiredPowerLabel: "Benötigte Leistung",
    flatMassLabel: "Masse (Tonnen)",
    drivesHeading: "Antriebe",
    driveChartTitle: "Antriebsdiagramm",
    driveChartSubtitle: "Zum Zoomen ziehen, Doppelklick zum Zurücksetzen. Für Details mit der Maus darüber; Beschriftungen umschalten, um zu entschlacken.",
    backToTechTree: "Zurück zum Technologiebaum",
    closeLabel: "Schließen",
    cruiseThrust: "Reiseschub",
    combatThrust: "Kampfschub",
    showLabels: "Beschriftungen anzeigen",
    loadingDrives: "Antriebe werden geladen…",
    exhaustVelocityLabel: "Austrittsgeschwindigkeit",
    unknownDrive: "Unbekannter Antrieb",
    notAvailable: "N/A",
    orLabel: "oder",
    andLabel: "und",
    factionProjectTitle: "Fraktionsprojekt",
    globalResearchTitle: "Globale Forschung",
    claimGained: "{nation} erhebt Anspruch auf {region}",
    adjacencyFriendly: "{region1} und {region2} gelten nun als angrenzend für freundlichen Verkehr",
    adjacencyGeneral: "{region1} und {region2} gelten nun als angrenzend",
    scenarioLabel: "Szenario",
    settingsMenuLabel: "Einstellungen",
    scenarioSettingsDiscovery: "Szenarien sind in den Einstellungen verfügbar",
    settingsCurrentScenario: "Einstellungen — aktuelles Szenario: {scenario}",
    scenarioStandard: "Standard",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Kaputte Erde",
    scenario2003Fallback: "2003-Szenario",
    scenarioBrokenEarthFallback: "„Kaputte Erde“-Szenario",
    scenarioTreeStatus: "Szenario: {scenario}",
    scenarioViewingStatus: "Angezeigt wird {active} · {target} wird geladen…",
    scenarioLoadingStatus: "{target} wird geladen…",
    scenarioLoadError: "{scenario} konnte nicht geladen werden. Der vorherige Forschungsbaum bleibt aktiv.",
    scenarioInitialLoadError: "{scenario} konnte nicht geladen werden. Bitte erneut versuchen.",
    darkSkiesDlc: "Dark Skies-DLC",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Dark-Skies-Erweiterung",
    scenarioVersion: "Version für {scenario}",
    technologyGraphAccessible: "Technologiegraph für {scenario}. Eine Raute kennzeichnet Knoten, die durch das Dark Skies-DLC hinzugefügt wurden.",
};

const espUi: LocalizedUi = {
    adjacencies: "Adyacencias",
    baseAvailabilityChance: "Probabilidad Base de Disponibilidad",
    claims: "Afirmaciones",
    claimsScenario: "Inicio en {year}",
    completableOnceGlobally: "Completable una vez globalmente",
    completionQuote: "Cita de Finalización",
    completionText: "Texto de Finalización",
    cost: "Costo",
    effects: "Efectos",
    endgameTech: "Tecnología de fin de juego",
    factionAlways: "Siempre disponible para",
    factionPrereq: "Solo disponible para",
    fullTextSearch: "Búsqueda de texto completo",
    hiddenEffect: "Efecto oculto: ",
    initialUnlockChance: "Probabilidad Inicial de Desbloqueo",
    markDone: "Marcar como hecho",
    markUndone: "Desmarcar",
    clearAllProgress: "Borrar Todo Progreso",
    clearAllProgressTooltip: "Borra todo el progreso de investigación y recarga la página",
    maximumUnlockChance: "Probabilidad Máxima de Desbloqueo",
    milestoneNeeded: "Hito Necesario",
    modulesUnlocked: "Módulos Desbloqueados",
    monthlyUnlockChanceIncrease: "Aumento Mensual de Probabilidad de Desbloqueo",
    orgGranted: "Organización Otorgada",
    orgsAddedToMarket: "Organizaciones Añadidas al Mercado",
    repeatable: "Repetible",
    requiredResearch: "Investigación Requerida",
    resourcesGranted: "Recursos Otorgados",
    search: "Buscar",
    seeEntireTree: "Ver árbol completo",
    seeTreeForThisNode: "Ver árbol para este nodo",
    browseGamefiles: "Explorar archivos del juego",
    projectSourceCode: "Código fuente del proyecto",
    showProjects: "Mostrar Proyectos",
    summary: "Resumen",
    totalTreeCost: "Costo Total del Árbol",
    traits: "Rasgos de Consejero Disponibles",
    unblocksOneOrMoreModules: "Desbloquea uno o más módulos.",
    unblocksResearch: "Desbloquea Investigación",
    randomFaction: "Aleatorio",
    costBreakdownTooltip: "Clic para ver el desglose de costos tecnológicos",
    copyToClipboard: "Copiar al portapapeles",
    copiedLabel: "¡Copiado!",
    fuelPerTank: "Combustible por tanque",
    weightedBuildMaterialsLabel: "Materiales de construcción",
    driveSpecsShared: "Especificaciones del motor (compartido)",
    driveColumnLabel: "Motor",
    thrustersLabel: "Propulsores",
    thrustNLabel: "Empuje (N)",
    thrustRatingGWLabel: "Potencia de empuje (GW)",
    requiredPowerLabel: "Potencia requerida",
    flatMassLabel: "Masa (toneladas)",
    drivesHeading: "Motores",
    driveChartTitle: "Gráfico de motores",
    driveChartSubtitle: "Arrastra para hacer zoom, doble clic para restablecer. Pasa el ratón para ver detalles; alterna etiquetas para despejar.",
    backToTechTree: "Volver al árbol tecnológico",
    closeLabel: "Cerrar",
    cruiseThrust: "Empuje de crucero",
    combatThrust: "Empuje de combate",
    showLabels: "Mostrar etiquetas",
    loadingDrives: "Cargando motores…",
    exhaustVelocityLabel: "Velocidad de escape",
    unknownDrive: "Motor desconocido",
    notAvailable: "N/A",
    orLabel: "o",
    andLabel: "y",
    factionProjectTitle: "Proyecto de Facción",
    globalResearchTitle: "Investigación Global",
    claimGained: "{nation} obtiene una reclamación sobre {region}",
    adjacencyFriendly: "{region1} y {region2} ahora se consideran adyacentes para tráfico amistoso",
    adjacencyGeneral: "{region1} y {region2} ahora se consideran adyacentes",
    scenarioLabel: "Escenario",
    settingsMenuLabel: "Ajustes",
    scenarioSettingsDiscovery: "Hay escenarios disponibles en Ajustes",
    settingsCurrentScenario: "Ajustes — escenario actual: {scenario}",
    scenarioStandard: "Estándar",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Tierra fracturada",
    scenario2003Fallback: "Escenario 2003",
    scenarioBrokenEarthFallback: "Escenario Tierra fracturada",
    scenarioTreeStatus: "Escenario: {scenario}",
    scenarioViewingStatus: "Mostrando {active} · Cargando {target}…",
    scenarioLoadingStatus: "Cargando {target}…",
    scenarioLoadError: "No se pudo cargar {scenario}. El árbol anterior sigue activo.",
    scenarioInitialLoadError: "No se pudo cargar {scenario}. Inténtalo de nuevo.",
    darkSkiesDlc: "DLC Dark Skies",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Contenido añadido de Dark Skies",
    scenarioVersion: "Versión de {scenario}",
    technologyGraphAccessible: "Grafo tecnológico de {scenario}. Un rombo marca los nodos añadidos por el DLC Dark Skies.",
};

const frUi: LocalizedUi = {
    adjacencies: "Adjacences",
    baseAvailabilityChance: "Chance de disponibilité de base",
    claims: "Revendications",
    claimsScenario: "Départ {year}",
    completableOnceGlobally: "Complétable une fois globalement",
    completionQuote: "Citation de fin",
    completionText: "Texte de fin",
    cost: "Coût",
    effects: "Effets",
    endgameTech: "Technologie de fin de partie",
    factionAlways: "Toujours disponible pour",
    factionPrereq: "Uniquement disponible pour",
    fullTextSearch: "Recherche en texte intégral",
    hiddenEffect: "Effet caché : ",
    initialUnlockChance: "Chance de déverrouillage initiale",
    markDone: "Marquer comme fait",
    markUndone: "Marquer comme non fait",
    clearAllProgress: "Effacer Tous Progrès",
    clearAllProgressTooltip: "Efface tous les progrès de recherche et recharge la page",
    maximumUnlockChance: "Chance de déverrouillage maximale",
    milestoneNeeded: "Jalon nécessaire",
    modulesUnlocked: "Modules déverrouillés",
    monthlyUnlockChanceIncrease: "Augmentation mensuelle de la chance de déverrouillage",
    orgGranted: "Organisation accordée",
    orgsAddedToMarket: "Organisations ajoutées au marché",
    repeatable: "Répétable",
    requiredResearch: "Recherche requise",
    resourcesGranted: "Ressources accordées",
    search: "Rechercher",
    seeEntireTree: "Voir l'arbre entier",
    seeTreeForThisNode: "Voir l'arbre pour ce nœud",
    browseGamefiles: "Parcourir les fichiers du jeu",
    projectSourceCode: "Code source du projet",
    showProjects: "Afficher les projets",
    summary: "Résumé",
    totalTreeCost: "Coût total de l'arbre",
    traits: "Traits de conseiller disponibles",
    unblocksOneOrMoreModules: "Débloque un ou plusieurs modules.",
    unblocksResearch: "Débloque la recherche",
    randomFaction: "Aléatoire",
    costBreakdownTooltip: "Cliquez pour voir la répartition des coûts technologiques",
    copyToClipboard: "Copier dans le presse-papiers",
    copiedLabel: "Copié !",
    fuelPerTank: "Carburant par réservoir",
    weightedBuildMaterialsLabel: "Matériaux de construction",
    driveSpecsShared: "Spécifications du moteur (partagées)",
    driveColumnLabel: "Moteur",
    thrustersLabel: "Propulseurs",
    thrustNLabel: "Poussée (N)",
    thrustRatingGWLabel: "Puissance de poussée (GW)",
    requiredPowerLabel: "Puissance requise",
    flatMassLabel: "Masse (tonnes)",
    drivesHeading: "Moteurs",
    driveChartTitle: "Graphique des moteurs",
    driveChartSubtitle: "Glissez pour zoomer, double-cliquez pour réinitialiser. Survolez pour les détails ; basculez les étiquettes pour désencombrer.",
    backToTechTree: "Retour à l'arbre technologique",
    closeLabel: "Fermer",
    cruiseThrust: "Poussée de croisière",
    combatThrust: "Poussée de combat",
    showLabels: "Afficher les étiquettes",
    loadingDrives: "Chargement des moteurs…",
    exhaustVelocityLabel: "Vitesse d'éjection",
    unknownDrive: "Moteur inconnu",
    notAvailable: "N/A",
    orLabel: "ou",
    andLabel: "et",
    factionProjectTitle: "Projet de Faction",
    globalResearchTitle: "Recherche Globale",
    claimGained: "{nation} revendique {region}",
    adjacencyFriendly: "{region1} et {region2} sont maintenant considérés comme adjacents pour le trafic allié",
    adjacencyGeneral: "{region1} et {region2} sont maintenant considérés comme adjacents",
    scenarioLabel: "Scénario",
    settingsMenuLabel: "Paramètres",
    scenarioSettingsDiscovery: "Des scénarios sont disponibles dans les paramètres",
    settingsCurrentScenario: "Paramètres — scénario actuel : {scenario}",
    scenarioStandard: "Standard",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Terre brisée",
    scenario2003Fallback: "Scénario 2003",
    scenarioBrokenEarthFallback: "Scénario Terre brisée",
    scenarioTreeStatus: "Scénario : {scenario}",
    scenarioViewingStatus: "Affichage de {active} · Chargement de {target}…",
    scenarioLoadingStatus: "Chargement de {target}…",
    scenarioLoadError: "Impossible de charger {scenario}. L’arbre précédent reste actif.",
    scenarioInitialLoadError: "Impossible de charger {scenario}. Réessayez.",
    darkSkiesDlc: "DLC Dark Skies",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Ajout Dark Skies",
    scenarioVersion: "Version {scenario}",
    technologyGraphAccessible: "Graphe technologique pour {scenario}. Un losange signale les nœuds ajoutés par le DLC Dark Skies.",
};

const jpnUi: LocalizedUi = {
    adjacencies: "隣接関係",
    baseAvailabilityChance: "基本利用可能性",
    claims: "主張",
    claimsScenario: "{year}年開始",
    completableOnceGlobally: "全体で一度だけ完了可能",
    completionQuote: "完了時の引用",
    completionText: "完了テキスト",
    cost: "コスト",
    effects: "効果",
    endgameTech: "エンドゲーム技術",
    factionAlways: "常に利用可能",
    factionPrereq: "限定利用可能",
    fullTextSearch: "全文検索",
    hiddenEffect: "隠し効果：",
    initialUnlockChance: "初期解除確率",
    markDone: "完了としてマーク",
    markUndone: "未完了としてマーク",
    clearAllProgress: "全進歩をクリア",
    clearAllProgressTooltip: "すべての研究進歩をクリアしてページを再読み込みします",
    maximumUnlockChance: "最大解除確率",
    milestoneNeeded: "必要なマイルストーン",
    modulesUnlocked: "解除されたモジュール",
    monthlyUnlockChanceIncrease: "月間解除確率増加",
    orgGranted: "付与される組織",
    orgsAddedToMarket: "市場に追加される組織",
    repeatable: "繰り返し可能",
    requiredResearch: "必要な研究",
    resourcesGranted: "付与される資源",
    search: "検索",
    seeEntireTree: "ツリー全体を表示",
    seeTreeForThisNode: "このノードのツリーを表示",
    browseGamefiles: "ゲームファイルを閲覧",
    projectSourceCode: "プロジェクトソースコード",
    showProjects: "プロジェクトを表示",
    summary: "概要",
    totalTreeCost: "ツリー総コスト",
    traits: "利用可能な評議員特性",
    unblocksOneOrMoreModules: "1つ以上のモジュールをアンロックします。",
    unblocksResearch: "研究をアンロック",
    randomFaction: "ランダム",
    costBreakdownTooltip: "クリックして技術コストの内訳を表示",
    copyToClipboard: "クリップボードにコピー",
    copiedLabel: "コピーしました！",
    fuelPerTank: "タンクあたりの燃料",
    weightedBuildMaterialsLabel: "建造素材",
    driveSpecsShared: "エンジン仕様（共通）",
    driveColumnLabel: "エンジン",
    thrustersLabel: "スラスター",
    thrustNLabel: "推力 (N)",
    thrustRatingGWLabel: "推力定格 (GW)",
    requiredPowerLabel: "必要電力",
    flatMassLabel: "質量 (トン)",
    drivesHeading: "エンジン",
    driveChartTitle: "ドライブチャート",
    driveChartSubtitle: "ドラッグでズーム、ダブルクリックでリセット。詳細はホバー、ラベルの表示を切り替えて見やすく。",
    backToTechTree: "技術ツリーに戻る",
    closeLabel: "閉じる",
    cruiseThrust: "巡航推力",
    combatThrust: "戦闘推力",
    showLabels: "ラベルを表示",
    loadingDrives: "ドライブを読み込み中…",
    exhaustVelocityLabel: "排気速度",
    unknownDrive: "不明なドライブ",
    notAvailable: "N/A",
    orLabel: "または",
    andLabel: "かつ",
    factionProjectTitle: "勢力プロジェクト",
    globalResearchTitle: "グローバル研究",
    claimGained: "{nation}が{region}の領有権を主張",
    adjacencyFriendly: "{region1}と{region2}は友好的な交通において隣接とみなされます",
    adjacencyGeneral: "{region1}と{region2}は隣接とみなされます",
    scenarioLabel: "シナリオ",
    settingsMenuLabel: "設定",
    scenarioSettingsDiscovery: "設定でシナリオを選択できます",
    settingsCurrentScenario: "設定 — 現在のシナリオ: {scenario}",
    scenarioStandard: "標準",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "崩壊した地球",
    scenario2003Fallback: "シナリオ2003",
    scenarioBrokenEarthFallback: "シナリオ：崩壊した地球",
    scenarioTreeStatus: "シナリオ: {scenario}",
    scenarioViewingStatus: "{active}を表示中 · {target}を読み込み中…",
    scenarioLoadingStatus: "{target}を読み込み中…",
    scenarioLoadError: "{scenario}を読み込めません。前の技術ツリーを引き続き表示します。",
    scenarioInitialLoadError: "{scenario}を読み込めません。もう一度お試しください。",
    darkSkiesDlc: "Dark Skies DLC",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Dark Skies追加要素",
    scenarioVersion: "{scenario}版",
    technologyGraphAccessible: "{scenario}の技術グラフ。ひし形はDark Skies DLCで追加されたノードを示します。",
};

const polUi: LocalizedUi = {
    adjacencies: "Sąsiedztwa",
    baseAvailabilityChance: "Podstawowa szansa dostępności",
    claims: "Roszczenia",
    claimsScenario: "Start {year}",
    completableOnceGlobally: "Ukończalne tylko raz globalnie",
    completionQuote: "Cytat przy ukończeniu",
    completionText: "Tekst ukończenia",
    cost: "Koszt",
    effects: "Efekty",
    endgameTech: "Technologia końca gry",
    factionAlways: "Zawsze dostępne dla",
    factionPrereq: "Dostępne tylko dla",
    fullTextSearch: "Wyszukiwanie pełnotekstowe",
    hiddenEffect: "Ukryty efekt: ",
    initialUnlockChance: "Początkowa szansa odblokowania",
    markDone: "Oznacz jako ukończone",
    markUndone: "Oznacz jako nieukończone",
    clearAllProgress: "Wyczyść Cały Postęp",
    clearAllProgressTooltip: "Czyści cały postęp badań i przeładowuje stronę",
    maximumUnlockChance: "Maksymalna szansa odblokowania",
    milestoneNeeded: "Wymagany kamień milowy",
    modulesUnlocked: "Odblokowane moduły",
    monthlyUnlockChanceIncrease: "Miesięczny wzrost szansy odblokowania",
    orgGranted: "Przyznana organizacja",
    orgsAddedToMarket: "Organizacje dodane do rynku",
    repeatable: "Powtarzalne",
    requiredResearch: "Wymagane badania",
    resourcesGranted: "Przyznane zasoby",
    search: "Szukaj",
    seeEntireTree: "Zobacz całe drzewo",
    seeTreeForThisNode: "Zobacz drzewo dla tego węzła",
    browseGamefiles: "Przeglądaj pliki gry",
    projectSourceCode: "Kod źródłowy projektu",
    showProjects: "Pokaż projekty",
    summary: "Podsumowanie",
    totalTreeCost: "Całkowity koszt drzewa",
    traits: "Dostępne cechy radnych",
    unblocksOneOrMoreModules: "Odblokowuje jeden lub więcej modułów.",
    unblocksResearch: "Odblokowuje badania",
    randomFaction: "Losowo",
    costBreakdownTooltip: "Kliknij, aby zobaczyć podział kosztów technologii",
    copyToClipboard: "Kopiuj do schowka",
    copiedLabel: "Skopiowano!",
    fuelPerTank: "Paliwo na zbiornik",
    weightedBuildMaterialsLabel: "Materiały budowlane",
    driveSpecsShared: "Specyfikacja napędu (wspólna)",
    driveColumnLabel: "Napęd",
    thrustersLabel: "Silniki",
    thrustNLabel: "Ciąg (N)",
    thrustRatingGWLabel: "Moc ciągu (GW)",
    requiredPowerLabel: "Wymagana moc",
    flatMassLabel: "Masa (ton)",
    drivesHeading: "Napędy",
    driveChartTitle: "Wykres napędów",
    driveChartSubtitle: "Przeciągnij, aby przybliżyć, dwuklik przywraca. Najedź, aby zobaczyć szczegóły; przełączaj etykiety, by ograniczyć bałagan.",
    backToTechTree: "Wróć do drzewa technologii",
    closeLabel: "Zamknij",
    cruiseThrust: "Ciąg przelotowy",
    combatThrust: "Ciąg bojowy",
    showLabels: "Pokaż etykiety",
    loadingDrives: "Ładowanie napędów…",
    exhaustVelocityLabel: "Prędkość wylotowa",
    unknownDrive: "Nieznany napęd",
    notAvailable: "N/A",
    orLabel: "lub",
    andLabel: "i",
    factionProjectTitle: "Projekt Frakcji",
    globalResearchTitle: "Globalne Badania",
    claimGained: "{nation} uzyskuje roszczenie do {region}",
    adjacencyFriendly: "{region1} i {region2} są teraz uznawane za sąsiadujące dla ruchu sojuszniczego",
    adjacencyGeneral: "{region1} i {region2} są teraz uznawane za sąsiadujące",
    scenarioLabel: "Scenariusz",
    settingsMenuLabel: "Ustawienia",
    scenarioSettingsDiscovery: "Scenariusze są dostępne w ustawieniach",
    settingsCurrentScenario: "Ustawienia — bieżący scenariusz: {scenario}",
    scenarioStandard: "Standardowy",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Zniszczona Ziemia",
    scenario2003Fallback: "Scenariusz 2003",
    scenarioBrokenEarthFallback: "Scenariusz Zniszczonej Ziemi",
    scenarioTreeStatus: "Scenariusz: {scenario}",
    scenarioViewingStatus: "Wyświetlanie {active} · Wczytywanie {target}…",
    scenarioLoadingStatus: "Wczytywanie {target}…",
    scenarioLoadError: "Nie udało się wczytać {scenario}. Poprzednie drzewo pozostaje aktywne.",
    scenarioInitialLoadError: "Nie udało się wczytać {scenario}. Spróbuj ponownie.",
    darkSkiesDlc: "DLC Dark Skies",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Element dodany w Dark Skies",
    scenarioVersion: "Wersja: {scenario}",
    technologyGraphAccessible: "Graf technologii dla {scenario}. Romb oznacza węzły dodane przez DLC Dark Skies.",
};

const porUi: LocalizedUi = {
    adjacencies: "Adjacências",
    baseAvailabilityChance: "Chance Base de Disponibilidade",
    claims: "Reivindicações",
    claimsScenario: "Início em {year}",
    completableOnceGlobally: "Completável uma vez globalmente",
    completionQuote: "Citação de Conclusão",
    completionText: "Texto de Conclusão",
    cost: "Custo",
    effects: "Efeitos",
    endgameTech: "Tecnologia de fim de jogo",
    factionAlways: "Sempre disponível para",
    factionPrereq: "Disponível apenas para",
    fullTextSearch: "Pesquisa de texto completo",
    hiddenEffect: "Efeito oculto: ",
    initialUnlockChance: "Chance Inicial de Desbloqueio",
    markDone: "Marcar como concluído",
    markUndone: "Marcar como não concluído",
    clearAllProgress: "Limpar Todo Progresso",
    clearAllProgressTooltip: "Limpa todo o progresso de pesquisa e recarrega a página",
    maximumUnlockChance: "Chance Máxima de Desbloqueio",
    milestoneNeeded: "Marco Necessário",
    modulesUnlocked: "Módulos Desbloqueados",
    monthlyUnlockChanceIncrease: "Aumento Mensal da Chance de Desbloqueio",
    orgGranted: "Organização Concedida",
    orgsAddedToMarket: "Organizações Adicionadas ao Mercado",
    repeatable: "Repetível",
    requiredResearch: "Pesquisa Necessária",
    resourcesGranted: "Recursos Concedidos",
    search: "Pesquisar",
    seeEntireTree: "Ver árvore completa",
    seeTreeForThisNode: "Ver árvore para este nó",
    browseGamefiles: "Navegar arquivos do jogo",
    projectSourceCode: "Código fonte do projeto",
    showProjects: "Mostrar Projetos",
    summary: "Resumo",
    totalTreeCost: "Custo Total da Árvore",
    traits: "Características de Conselheiro Disponíveis",
    unblocksOneOrMoreModules: "Desbloqueia um ou mais módulos.",
    unblocksResearch: "Desbloqueia Pesquisa",
    randomFaction: "Aleatório",
    costBreakdownTooltip: "Clique para ver o detalhamento dos custos de tecnologia",
    copyToClipboard: "Copiar para a área de transferência",
    copiedLabel: "Copiado!",
    fuelPerTank: "Combustível por tanque",
    weightedBuildMaterialsLabel: "Materiais de construção",
    driveSpecsShared: "Especificações do motor (compartilhado)",
    driveColumnLabel: "Motor",
    thrustersLabel: "Propulsores",
    thrustNLabel: "Empuxo (N)",
    thrustRatingGWLabel: "Potência de empuxo (GW)",
    requiredPowerLabel: "Potência necessária",
    flatMassLabel: "Massa (toneladas)",
    drivesHeading: "Motores",
    driveChartTitle: "Gráfico de propulsores",
    driveChartSubtitle: "Arraste para ampliar, clique duas vezes para reiniciar. Passe o mouse para ver detalhes; alterne rótulos para reduzir a bagunça.",
    backToTechTree: "Voltar para a árvore tecnológica",
    closeLabel: "Fechar",
    cruiseThrust: "Empuxo de cruzeiro",
    combatThrust: "Empuxo de combate",
    showLabels: "Mostrar rótulos",
    loadingDrives: "Carregando motores…",
    exhaustVelocityLabel: "Velocidade de exaustão",
    unknownDrive: "Motor desconhecido",
    notAvailable: "N/A",
    orLabel: "ou",
    andLabel: "e",
    factionProjectTitle: "Projeto de Facção",
    globalResearchTitle: "Pesquisa Global",
    claimGained: "{nation} obtém uma reivindicação sobre {region}",
    adjacencyFriendly: "{region1} e {region2} agora são considerados adjacentes para tráfego amigável",
    adjacencyGeneral: "{region1} e {region2} agora são considerados adjacentes",
    scenarioLabel: "Cenário",
    settingsMenuLabel: "Configurações",
    scenarioSettingsDiscovery: "Há cenários disponíveis nas configurações",
    settingsCurrentScenario: "Configurações — cenário atual: {scenario}",
    scenarioStandard: "Padrão",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Terra Fragmentada",
    scenario2003Fallback: "Cenário 2003",
    scenarioBrokenEarthFallback: "Cenário Terra Fragmentada",
    scenarioTreeStatus: "Cenário: {scenario}",
    scenarioViewingStatus: "Exibindo {active} · Carregando {target}…",
    scenarioLoadingStatus: "Carregando {target}…",
    scenarioLoadError: "Não foi possível carregar {scenario}. A árvore anterior permanece ativa.",
    scenarioInitialLoadError: "Não foi possível carregar {scenario}. Tente novamente.",
    darkSkiesDlc: "DLC Dark Skies",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Adição de Dark Skies",
    scenarioVersion: "Versão {scenario}",
    technologyGraphAccessible: "Grafo de tecnologias de {scenario}. Um losango marca os nós adicionados pelo DLC Dark Skies.",
};

const korUi: LocalizedUi = {
    adjacencies: "인접 관계",
    baseAvailabilityChance: "기본 가용 확률",
    claims: "영유권",
    claimsScenario: "{year}년 시작",
    completableOnceGlobally: "전 세계에서 한 번만 완료 가능",
    completionQuote: "완료 인용구",
    completionText: "완료 텍스트",
    cost: "비용",
    effects: "효과",
    endgameTech: "엔드게임 기술",
    factionAlways: "항상 사용 가능한 세력",
    factionPrereq: "사용 가능한 세력 제한",
    fullTextSearch: "전체 텍스트 검색",
    hiddenEffect: "숨겨진 효과: ",
    initialUnlockChance: "초기 해제 확률",
    markDone: "완료 표시",
    markUndone: "완료 취소",
    clearAllProgress: "모든 진행도 초기화",
    clearAllProgressTooltip: "모든 연구 진행도를 초기화하고 페이지를 새로 고칩니다",
    maximumUnlockChance: "최대 해제 확률",
    milestoneNeeded: "필요한 이정표",
    modulesUnlocked: "해제된 모듈",
    monthlyUnlockChanceIncrease: "월간 해제 확률 증가",
    orgGranted: "획득한 조직",
    orgsAddedToMarket: "시장에 추가된 조직",
    repeatable: "반복 가능",
    requiredResearch: "필요 연구",
    resourcesGranted: "획득 자원",
    search: "검색",
    seeEntireTree: "전체 트리 보기",
    seeTreeForThisNode: "이 노드의 트리 보기",
    browseGamefiles: "게임 파일 탐색",
    projectSourceCode: "프로젝트 소스 코드",
    showProjects: "프로젝트 표시",
    summary: "요약",
    totalTreeCost: "트리 총 비용",
    traits: "사용 가능한 고문 특성",
    unblocksOneOrMoreModules: "하나 이상의 모듈을 해제합니다.",
    unblocksResearch: "연구를 해제",
    randomFaction: "무작위",
    costBreakdownTooltip: "기술 비용 내역을 보려면 클릭하세요",
    copyToClipboard: "클립보드에 복사",
    copiedLabel: "복사됨!",
    fuelPerTank: "탱크당 연료",
    weightedBuildMaterialsLabel: "건조 자재",
    driveSpecsShared: "엔진 사양 (공유)",
    driveColumnLabel: "엔진",
    thrustersLabel: "추진기",
    thrustNLabel: "추력 (N)",
    thrustRatingGWLabel: "추력 등급 (GW)",
    requiredPowerLabel: "필요 전력",
    flatMassLabel: "질량 (톤)",
    drivesHeading: "엔진",
    driveChartTitle: "드라이브 차트",
    driveChartSubtitle: "드래그하여 확대, 더블 클릭으로 초기화. 세부 정보는 호버로 확인하고 레이블을 전환해 정돈하세요.",
    backToTechTree: "기술 트리로 돌아가기",
    closeLabel: "닫기",
    cruiseThrust: "순항 추력",
    combatThrust: "전투 추력",
    showLabels: "레이블 표시",
    loadingDrives: "엔진 불러오는 중…",
    exhaustVelocityLabel: "배기 속도",
    unknownDrive: "알 수 없는 엔진",
    notAvailable: "N/A",
    orLabel: "또는",
    andLabel: "그리고",
    factionProjectTitle: "세력 프로젝트",
    globalResearchTitle: "글로벌 연구",
    claimGained: "{nation}이(가) {region}에 대한 영유권을 획득",
    adjacencyFriendly: "{region1}과(와) {region2}은(는) 이제 우호적 교통을 위해 인접한 것으로 간주됩니다",
    adjacencyGeneral: "{region1}과(와) {region2}은(는) 이제 인접한 것으로 간주됩니다",
    scenarioLabel: "시나리오",
    settingsMenuLabel: "설정",
    scenarioSettingsDiscovery: "설정에서 시나리오를 선택할 수 있습니다",
    settingsCurrentScenario: "설정 — 현재 시나리오: {scenario}",
    scenarioStandard: "표준",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "붕괴된 지구",
    scenario2003Fallback: "2003 시나리오",
    scenarioBrokenEarthFallback: "붕괴된 지구 시나리오",
    scenarioTreeStatus: "시나리오: {scenario}",
    scenarioViewingStatus: "{active} 보는 중 · {target} 불러오는 중…",
    scenarioLoadingStatus: "{target} 불러오는 중…",
    scenarioLoadError: "{scenario}을(를) 불러올 수 없습니다. 이전 트리를 계속 표시합니다.",
    scenarioInitialLoadError: "{scenario}을(를) 불러올 수 없습니다. 다시 시도하세요.",
    darkSkiesDlc: "Dark Skies DLC",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Dark Skies 추가 콘텐츠",
    scenarioVersion: "{scenario} 버전",
    technologyGraphAccessible: "{scenario} 기술 그래프. 마름모는 Dark Skies DLC에서 추가된 노드를 나타냅니다.",
};

const rusUi: LocalizedUi = {
    adjacencies: "Смежности",
    baseAvailabilityChance: "Базовый шанс доступности",
    claims: "Претензии",
    claimsScenario: "Старт {year}",
    completableOnceGlobally: "Завершается только один раз во всём мире",
    completionQuote: "Цитата при завершении",
    completionText: "Текст завершения",
    cost: "Стоимость",
    effects: "Эффекты",
    endgameTech: "Финальная технология",
    factionAlways: "Всегда доступно для",
    factionPrereq: "Доступно только для",
    fullTextSearch: "Полнотекстовый поиск",
    hiddenEffect: "Скрытый эффект: ",
    initialUnlockChance: "Начальный шанс разблокировки",
    markDone: "Отметить выполненным",
    markUndone: "Отметить невыполненным",
    clearAllProgress: "Сбросить весь прогресс",
    clearAllProgressTooltip: "Сбрасывает весь прогресс исследований и перезагружает страницу",
    maximumUnlockChance: "Максимальный шанс разблокировки",
    milestoneNeeded: "Требуемый рубеж",
    modulesUnlocked: "Разблокированные модули",
    monthlyUnlockChanceIncrease: "Ежемесячный прирост шанса разблокировки",
    orgGranted: "Полученная организация",
    orgsAddedToMarket: "Организации, добавленные на рынок",
    repeatable: "Повторяемое",
    requiredResearch: "Необходимое исследование",
    resourcesGranted: "Выданные ресурсы",
    search: "Поиск",
    seeEntireTree: "Показать всё дерево",
    seeTreeForThisNode: "Показать дерево для этого узла",
    browseGamefiles: "Просмотр файлов игры",
    projectSourceCode: "Исходный код проекта",
    showProjects: "Показать проекты",
    summary: "Сводка",
    totalTreeCost: "Общая стоимость дерева",
    traits: "Доступные черты советников",
    unblocksOneOrMoreModules: "Разблокирует один или несколько модулей.",
    unblocksResearch: "Разблокирует исследования",
    randomFaction: "Случайно",
    costBreakdownTooltip: "Нажмите, чтобы увидеть разбивку стоимости технологий",
    copyToClipboard: "Копировать в буфер обмена",
    copiedLabel: "Скопировано!",
    fuelPerTank: "Топливо на бак",
    weightedBuildMaterialsLabel: "Строительные материалы",
    driveSpecsShared: "Характеристики двигателя (общие)",
    driveColumnLabel: "Двигатель",
    thrustersLabel: "Двигатели",
    thrustNLabel: "Тяга (Н)",
    thrustRatingGWLabel: "Мощность тяги (ГВт)",
    requiredPowerLabel: "Требуемая мощность",
    flatMassLabel: "Масса (тонн)",
    drivesHeading: "Двигатели",
    driveChartTitle: "График двигателей",
    driveChartSubtitle: "Перетащите для зума, двойной щелчок — сброс. Наведите для деталей; переключайте подписи, чтобы убрать лишнее.",
    backToTechTree: "Назад к техдереву",
    closeLabel: "Закрыть",
    cruiseThrust: "Крейсерская тяга",
    combatThrust: "Боевая тяга",
    showLabels: "Показывать метки",
    loadingDrives: "Загрузка двигателей…",
    exhaustVelocityLabel: "Скорость истечения",
    unknownDrive: "Неизвестный двигатель",
    notAvailable: "N/A",
    orLabel: "или",
    andLabel: "и",
    factionProjectTitle: "Проект фракции",
    globalResearchTitle: "Глобальное исследование",
    claimGained: "{nation} получает претензию на {region}",
    adjacencyFriendly: "{region1} и {region2} теперь считаются смежными для дружественного трафика",
    adjacencyGeneral: "{region1} и {region2} теперь считаются смежными",
    scenarioLabel: "Сценарий",
    settingsMenuLabel: "Настройки",
    scenarioSettingsDiscovery: "Сценарии доступны в настройках",
    settingsCurrentScenario: "Настройки — текущий сценарий: {scenario}",
    scenarioStandard: "Стандартный",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Расколотая Земля",
    scenario2003Fallback: "Сценарий-2003",
    scenarioBrokenEarthFallback: "Сценарий \"Расколотая Земля\"",
    scenarioTreeStatus: "Сценарий: {scenario}",
    scenarioViewingStatus: "Открыт {active} · Загрузка {target}…",
    scenarioLoadingStatus: "Загрузка {target}…",
    scenarioLoadError: "Не удалось загрузить {scenario}. Предыдущее дерево остаётся активным.",
    scenarioInitialLoadError: "Не удалось загрузить {scenario}. Повторите попытку.",
    darkSkiesDlc: "Дополнение Dark Skies",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Добавлено в Dark Skies",
    scenarioVersion: "Версия {scenario}",
    technologyGraphAccessible: "Граф технологий для {scenario}. Ромб отмечает узлы, добавленные дополнением Dark Skies.",
};

const ukrUi: LocalizedUi = {
    adjacencies: "Суміжності",
    baseAvailabilityChance: "Базовий шанс доступності",
    claims: "Претензії",
    claimsScenario: "Старт {year}",
    completableOnceGlobally: "Можна завершити лише один раз у світі",
    completionQuote: "Цитата завершення",
    completionText: "Текст завершення",
    cost: "Вартість",
    effects: "Ефекти",
    endgameTech: "Фінальна технологія",
    factionAlways: "Завжди доступно для",
    factionPrereq: "Доступно лише для",
    fullTextSearch: "Повнотекстовий пошук",
    hiddenEffect: "Прихований ефект: ",
    initialUnlockChance: "Початковий шанс розблокування",
    markDone: "Позначити завершеним",
    markUndone: "Позначити незавершеним",
    clearAllProgress: "Очистити весь прогрес",
    clearAllProgressTooltip: "Очищає весь прогрес досліджень і перезавантажує сторінку",
    maximumUnlockChance: "Максимальний шанс розблокування",
    milestoneNeeded: "Потрібний рубіж",
    modulesUnlocked: "Розблоковані модулі",
    monthlyUnlockChanceIncrease: "Щомісячне зростання шансу розблокування",
    orgGranted: "Надана організація",
    orgsAddedToMarket: "Організації, додані на ринок",
    repeatable: "Повторюване",
    requiredResearch: "Потрібне дослідження",
    resourcesGranted: "Надані ресурси",
    search: "Пошук",
    seeEntireTree: "Переглянути все дерево",
    seeTreeForThisNode: "Переглянути дерево для цього вузла",
    browseGamefiles: "Перегляд файлів гри",
    projectSourceCode: "Вихідний код проєкту",
    showProjects: "Показати проєкти",
    summary: "Підсумок",
    totalTreeCost: "Загальна вартість дерева",
    traits: "Доступні риси радників",
    unblocksOneOrMoreModules: "Розблоковує один або більше модулів.",
    unblocksResearch: "Розблоковує дослідження",
    randomFaction: "Випадково",
    costBreakdownTooltip: "Натисніть, щоб побачити розбивку вартості технологій",
    copyToClipboard: "Копіювати до буфера обміну",
    copiedLabel: "Скопійовано!",
    fuelPerTank: "Паливо на бак",
    weightedBuildMaterialsLabel: "Будівельні матеріали",
    driveSpecsShared: "Характеристики двигуна (спільні)",
    driveColumnLabel: "Двигун",
    thrustersLabel: "Двигуни",
    thrustNLabel: "Тяга (Н)",
    thrustRatingGWLabel: "Потужність тяги (ГВт)",
    requiredPowerLabel: "Потрібна потужність",
    flatMassLabel: "Маса (тонн)",
    drivesHeading: "Двигуни",
    driveChartTitle: "Графік двигунів",
    driveChartSubtitle: "Перетягніть, щоб масштабувати, подвійний клік скидає. Наведіть для деталей; перемикайте підписи, щоб прибрати зайве.",
    backToTechTree: "Назад до дерева технологій",
    closeLabel: "Закрити",
    cruiseThrust: "Крейсерська тяга",
    combatThrust: "Бойова тяга",
    showLabels: "Показувати мітки",
    loadingDrives: "Завантаження двигунів…",
    exhaustVelocityLabel: "Швидкість викиду",
    unknownDrive: "Невідомий двигун",
    notAvailable: "N/A",
    orLabel: "або",
    andLabel: "і",
    factionProjectTitle: "Проєкт фракції",
    globalResearchTitle: "Глобальне дослідження",
    claimGained: "{nation} отримує претензію на {region}",
    adjacencyFriendly: "{region1} і {region2} тепер вважаються суміжними для дружнього трафіку",
    adjacencyGeneral: "{region1} і {region2} тепер вважаються суміжними",
    scenarioLabel: "Сценарій",
    settingsMenuLabel: "Налаштування",
    scenarioSettingsDiscovery: "Сценарії доступні в налаштуваннях",
    settingsCurrentScenario: "Налаштування — поточний сценарій: {scenario}",
    scenarioStandard: "Стандартний",
    scenario2003Short: "2003",
    scenarioBrokenEarthShort: "Розбита Земля",
    scenario2003Fallback: "Сценарій 2003",
    scenarioBrokenEarthFallback: "Сценарій розбитої Землі",
    scenarioTreeStatus: "Сценарій: {scenario}",
    scenarioViewingStatus: "Перегляд {active} · Завантаження {target}…",
    scenarioLoadingStatus: "Завантаження {target}…",
    scenarioLoadError: "Не вдалося завантажити {scenario}. Попереднє дерево залишається активним.",
    scenarioInitialLoadError: "Не вдалося завантажити {scenario}. Спробуйте ще раз.",
    darkSkiesDlc: "Доповнення Dark Skies",
    darkSkiesName: "Dark Skies",
    darkSkiesAddition: "Додано в Dark Skies",
    scenarioVersion: "Версія {scenario}",
    technologyGraphAccessible: "Граф технологій для {scenario}. Ромб позначає вузли, додані доповненням Dark Skies.",
};

const stableAndExperimental: GameVersionCode[] = ['stable', 'experimental'];
// const experimentalOnly: GameVersionCode[] = ['experimental'];

export const Languages: Record<string, Language> = {
    en: { code: 'en', icon: '🇬🇧', name: 'English', uiTexts: englishUi, locale: 'en', availableVersions: stableAndExperimental },
    chs: { code: 'chs', icon: '🇨🇳', name: '简体中文', uiTexts: chsUi, locale: 'zh', availableVersions: stableAndExperimental },
    cht: { code: 'cht', icon: '🇨🇳', name: '繁體中文', uiTexts: chtUi, locale: 'zh', availableVersions: stableAndExperimental },
    deu: { code: 'deu', icon: '🇩🇪', name: 'Deutsch', uiTexts: deuUi, locale: 'de', availableVersions: stableAndExperimental },
    esp: { code: 'esp', icon: '🇪🇸', name: 'Español', uiTexts: espUi, locale: 'es', availableVersions: stableAndExperimental },
    fr: { code: 'fr', icon: '🇫🇷', name: 'Français', uiTexts: frUi, locale: 'fr', availableVersions: stableAndExperimental },
    jpn: { code: 'jpn', icon: '🇯🇵', name: '日本語', uiTexts: jpnUi, locale: 'ja', availableVersions: stableAndExperimental },
    pol: { code: 'pol', icon: '🇵🇱', name: 'Polski', uiTexts: polUi, locale: 'pl', availableVersions: stableAndExperimental },
    por: { code: 'por', icon: '🇧🇷', name: 'Português', uiTexts: porUi, locale: 'pt', availableVersions: stableAndExperimental },
    kor: { code: 'kor', icon: '🇰🇷', name: '한국어', uiTexts: korUi, locale: 'ko', availableVersions: stableAndExperimental },
    rus: { code: 'rus', icon: '🇷🇺', name: 'Русский', uiTexts: rusUi, locale: 'ru', availableVersions: stableAndExperimental },
    ukr: { code: 'ukr', icon: '🇺🇦', name: 'Українська', uiTexts: ukrUi, locale: 'uk', availableVersions: stableAndExperimental },
};

export const DefaultLanguage = Languages.en;
